pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common

/**
 * Grounding for the *local* assistant (customNixOSModules.localLlm). A small
 * model can't pick the right line out of the whole machine context and will
 * happily invent a key or a setting, so it is kept on rails:
 *
 * 1. Retrieval: for each question it gets the core facts plus only the facts
 *    matching it (keyword overlap weighted by rarity/IDF, light stemming,
 *    synonyms; templated facts are indexed on their distinctive part only;
 *    the previous question counts at half weight, for follow-ups).
 * 2. No model when it can't help: greetings get a fixed reply, and a question
 *    the facts don't cover (`coverage` < 0.2) gets "I don't know" with tips —
 *    no guessing.
 * 3. Answer checks (`guard`): a key the model made up, a missing or clearly
 *    worse key when a shortcut/how-to was asked → the matching binding; "is
 *    <module> enabled" / "is <package> installed" → from the configuration;
 *    a setting name or repository file that doesn't exist → flagged; an
 *    empty answer → the best fact; an answer with nothing checkable to a
 *    weakly covered question → marked as a guess.
 *
 * Facts: ~/.config/nixbook-shell/system-facts.json, generated by the Home
 * Manager module (customPkgs/nixbook-shell/scripts/assistant-facts.py).
 * Measured on a 12-question test with qwen2.5:1.5b: 12/12.
 */
Singleton {
    id: root

    readonly property bool ready: root.data !== null
    property var data: null
    property var _factWords: []
    property var _idf: ({})
    property real _maxIdf: 1
    property var _settingPaths: new Set()

    FileView {
        id: factsFile
        path: `${Directories.shellConfig}/system-facts.json`
        watchChanges: true
        onFileChanged: reload()
        onLoaded: root.load(factsFile.text())
        onLoadFailed: root.data = null
    }

    // What retrieval matches a fact on: the distinctive part only, so the
    // boilerplate of hundreds of templated facts ("The package … is
    // installed", "The shell setting … is set in Nix") doesn't drown words
    // like "shell", "setting" or "installed".
    function indexText(fact) {
        let m = fact.match(/^The shell setting (\S+) is set in Nix to (.*)\.$/);
        if (m) return `setting ${m[1].replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[._]/g, " ")} ${m[2]}`;
        m = fact.match(/^The package (\S+) is installed\.$/);
        if (m) return m[1].replace(/[-_.]/g, " ");
        return fact;
    }

    function load(text) {
        try {
            const d = JSON.parse(text);
            const fw = d.facts.map(f => new Set(root.words(root.indexText(f))));
            const df = {};
            for (const set of fw)
                for (const w of set)
                    df[w] = (df[w] ?? 0) + 1;
            const idf = {};
            for (const w in df)
                idf[w] = Math.log(d.facts.length / df[w]);
            root._factWords = fw;
            root._idf = idf;
            root._maxIdf = Math.log(d.facts.length);
            root._settingPaths = new Set(d.settingPaths ?? []);
            root.data = d;
        } catch (e) {
            console.warn("[ConfigAssistant] invalid system-facts.json:", e);
            root.data = null;
        }
    }

    readonly property var stopWords: new Set(("a an the is are am to of in on for with my me i do does how what which where when can could "
        + "should would it this that and or by from be use using key keyboard shortcut shortcuts bind binding press open get "
        + "spawn launch bring up mean meant want need please there way make you your").split(" "))
    readonly property var synonyms: ({
        "launcher": ["search", "app"], "app": ["launcher"], "screenshot": ["screen"], "float": ["floating"],
        "floating": ["tiled"], "terminal": ["kitty"], "lock": ["session"], "logout": ["log", "session"],
        "shutdown": ["shut", "power"], "poweroff": ["power"], "volume": ["audio"], "sound": ["audio", "volume"],
        "notification": ["notification"], "setting": ["configure"], "configure": ["setting"], "config": ["setting", "configure"],
        "configuration": ["setting", "configure"], "preference": ["setting"], "option": ["setting"],
        "disappear": ["hide"], "caffeine": ["idle"], "awake": ["idle", "display"], "sleep": ["suspend", "idle"],
        "screen": ["display"], "display": ["screen"], "copy": ["clipboard"], "paste": ["clipboard"],
        "capture": ["screenshot"], "snip": ["screenshot"], "log": ["session"], "restart": ["reboot"],
        "background": ["wallpaper"], "panel": ["sidebar"]
    })

    function stem(w) {
        if (w.length > 5 && w.endsWith("ing")) return w.slice(0, -3);
        if (w.length > 4 && w.endsWith("ed")) return w.slice(0, -2);
        if (w.length > 4 && /(s|x|z|ch|sh)es$/.test(w)) return w.slice(0, -2);
        if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss")) return w.slice(0, -1);
        return w;
    }
    function words(text) {
        // Single letters are noise ("what's" → "s", which matched Mod+S).
        return (text.toLowerCase().match(/[a-z0-9]+/g) ?? []).filter(w => w.length > 1)
            .map(w => root.stem(w)).filter(w => !root.stopWords.has(w));
    }

    // { facts: [{score, fact}] best first, coverage: 0..1 } — coverage is how
    // much of the question (IDF-weighted; words no fact contains weigh the
    // most) the best fact explains.
    function lookup(question, previous = "") {
        if (!root.data) return { facts: [], coverage: 0 };
        const direct = new Set(root.words(question));
        const context = new Set(root.words(previous).filter(w => !direct.has(w)));
        const extra = new Set();
        for (const w of direct)
            for (const s of (root.synonyms[w] ?? []))
                if (!direct.has(s)) extra.add(s);
        const weight = w => root._idf[w] ?? 0;
        const scored = [];
        root.data.facts.forEach((fact, i) => {
            const fw = root._factWords[i];
            let score = 0;
            for (const w of direct) if (fw.has(w)) score += weight(w);
            for (const w of extra) if (fw.has(w)) score += 0.5 * weight(w);
            for (const w of context) if (fw.has(w)) score += 0.5 * weight(w);
            if (score > 0) scored.push({ score, fact, i });
        });
        scored.sort((a, b) => b.score - a.score);
        if (scored.length === 0 || direct.size === 0) return { facts: scored.slice(0, 6), coverage: 0 };
        const top = scored[0].score;
        const facts = scored.filter(s => s.score >= 0.5 * top).slice(0, 6);
        // Coverage of the question by its best fact (synonyms count half).
        let total = 0, covered = 0;
        const best = root._factWords[scored[0].i];
        for (const w of direct) {
            const wt = root._idf[w] ?? root._maxIdf;
            total += wt;
            if (best.has(w)) covered += wt;
            else if ((root.synonyms[w] ?? []).some(s => best.has(s))) covered += wt / 2;
        }
        return { facts, coverage: total > 0 ? covered / total : 0 };
    }
    function retrieve(question, previous = "") {
        return root.lookup(question, previous).facts;
    }

    // System prompt for one question.
    function promptFor(question, previous = "") {
        if (!root.data) return "";
        const rel = root.retrieve(question, previous).map(s => `- ${s.fact}`);
        return root.data.core + (rel.length > 0 ? "\n" + rel.join("\n") : "");
    }

    readonly property string capabilities: Translation.tr("I can answer questions about this machine's configuration: keyboard shortcuts, which modules are enabled, which packages are installed, and where a setting is changed.")
    readonly property string askingTips: Translation.tr("Ask one thing at a time and name it, e.g. “What's the shortcut to open the app launcher?”, “Is tailscale enabled?”, “Is anki installed?” or “Where do I change the dock's pinned apps?”")

    // "Press Mod+D to open the app launcher." → "- **Mod+D**: open the app launcher"
    function formatBind(fact) {
        const m = fact.match(/^Press (\S+) to (.*?)\.?$/);
        return m ? `- **${m[1]}**: ${m[2]}` : `- ${fact}`;
    }
    // Listing questions ("show me all keybinds", "shortcuts for workspaces",
    // "which modules are enabled", "which packages are installed", "settings
    // set in Nix"): answered straight from the facts — complete and exact,
    // which a small model can't do reliably. null when not a listing question.
    function listReply(question) {
        const q = question.toLowerCase();
        const listing = /\b(all|list|every|cheat ?sheet|overview)\b/.test(q)
            || /\b(keybinds|shortcuts|bindings|hotkeys|modules|packages)\b/.test(q);
        if (!listing) return null;
        const facts = root.data.facts;
        if (/keybind|shortcut|hotkey|binding|\bkeys\b|key bind/.test(q)) {
            const binds = facts.filter(f => f.startsWith("Press "));
            const generic = new Set(["all", "list", "every", "each", "show", "available", "overview", "cheat", "sheet",
                "keybind", "hotkey", "shortcut", "binding", "key", "the", "me", "here", "have", "exist", "current", "configured"]);
            const topic = new Set(root.words(question).filter(w => !generic.has(w)));
            for (const w of [...topic])
                for (const s of (root.synonyms[w] ?? [])) topic.add(s);
            let selected = binds;
            if (topic.size > 0) {
                const matching = binds.filter(f => root.words(f).some(w => topic.has(w)));
                if (matching.length > 0) selected = matching;
            }
            const title = selected === binds
                ? Translation.tr("All keyboard shortcuts (%1, Mod = Super key):").arg(binds.length)
                : Translation.tr("Shortcuts matching your question (Mod = Super key):");
            return `${title}\n${selected.map(f => root.formatBind(f)).join("\n")}`;
        }
        if (/\bmodules?\b/.test(q)) {
            const off = root.data.modules.all.filter(m => !root.data.modules.enabled.includes(m));
            return Translation.tr("Enabled modules on %1:").arg(root.data.host ?? "this machine")
                + `\n${root.data.modules.enabled.join(", ")}\n\n`
                + Translation.tr("Available but not enabled:") + `\n${off.join(", ")}`;
        }
        if (/\bsettings?\b/.test(q) && /\bnix\b|pinned|locked/.test(q)) {
            const pinned = facts.filter(f => f.startsWith("The shell setting "))
                .map(f => f.replace(/^The shell setting (\S+) is set in Nix to (.*)\.$/, "- `$1` = `$2`"));
            return Translation.tr("Shell settings set in Nix (locked in the Settings window):") + `\n${pinned.join("\n")}`;
        }
        if (/\bpackages?\b|\binstalled\b/.test(q))
            return Translation.tr("Installed packages (%1):").arg(root.data.packages.length) + `\n${root.data.packages.join(", ")}`;
        return null;
    }

    // A reply that needs no model (greetings; listings; questions the
    // configuration doesn't cover), or null.
    function quickReply(question, previous = "") {
        if (!root.data) return null;
        const q = question.trim().toLowerCase();
        if (/^(hi|hello|hey|yo|hiya|good (morning|afternoon|evening)|bonjour|salut|coucou)\b[\s!.,?]*$/.test(q))
            return `${Translation.tr("Hi!")} ${root.capabilities}\n\n${root.askingTips}`;
        if (/^(thanks|thank you|thx|merci|ok|okay|cool|great|nice)\b[\s!.,]*$/.test(q))
            return Translation.tr("You're welcome!");
        const listing = root.listReply(question);
        if (listing !== null) return listing;
        // A module named in the question: answerable from the module lists.
        if (root.data.modules.all.some(m => new RegExp(`\\b${root.escapeRe(m.toLowerCase())}\\b`).test(q)))
            return null;
        const found = root.lookup(question, previous);
        if (found.facts.length === 0 || found.coverage < 0.2)
            return `${Translation.tr("I don't know: I couldn't find that in this machine's configuration.")} ${root.capabilities}\n\n${root.askingTips}`;
        return null;
    }

    readonly property var keyPattern: /(?:(?:Mod|Super|Ctrl|Control|Alt|Shift|Win(?:dows)?)\s*\+\s*)+[A-Za-z0-9_]+|\bPrint\b|XF86\w+/g
    function normKey(k) {
        return k.replace(/\s+/g, "").replace(/super|windows|win/gi, "Mod").toLowerCase();
    }
    function escapeRe(s) {
        return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }
    // All matches of a global regex (QML's JS engine has no String.matchAll).
    function allMatches(re, text) {
        const out = [];
        const g = new RegExp(re.source, re.flags.includes("g") ? re.flags : re.flags + "g");
        let m;
        while ((m = g.exec(text)) !== null) {
            out.push(m);
            if (m[0].length === 0) g.lastIndex += 1;
        }
        return out;
    }
    function yesNo(answer) {
        const m = answer.trim().match(/^\W*(\*\*)?(yes|no)\b/i);
        return m ? m[2].toLowerCase() === "yes" : null;
    }
    // Repository paths the answer may name: the profile files, module files
    // and the shared shell settings; anything else is probably invented.
    function knownPath(p) {
        const host = root.data.host ?? "";
        if (p.startsWith(`profiles/${host}/`) || p === "homeManagerModules/nixbookShellConfig/settings.nix"
                || p === "KEYBINDS.md" || p.startsWith("customPkgs/nixbook-shell/"))
            return true;
        const base = p.split("/").pop().replace(/\.nix$/, "");
        return /^(nixosModules|homeManagerModules)\//.test(p) && root.data.modules.all.includes(base);
    }

    // The answer to show: `answer`, or a corrected/annotated one.
    function guard(question, answer, previous = "") {
        if (!root.data) return answer;
        const found = root.lookup(question, previous);
        const scored = found.facts;
        const q = question.toLowerCase();
        if (answer.trim().length === 0)
            return scored.length > 0 ? Translation.tr("From your configuration: %1").arg(scored[0].fact)
                                     : Translation.tr("I don't know.");
        // A short follow-up ("i mean the shell menu") keeps the intent of the
        // question it refines.
        const followUp = previous.length > 0
            && (/^\s*(i mean|i meant|no\b|not that|what about|and\b|the\b|i said|actually|rather)/.test(q) || q.split(/\s+/).length <= 5);
        const intentText = followUp ? `${q} ${previous.toLowerCase()}` : q;
        const asked = /shortcut|keybind|hotkey|keyboard|\bkeys?\b|\bpress|\bbind/.test(intentText);
        const howTo = /^\s*(how|what should|can i|is there a way)/.test(q)
            || (followUp && /^\s*(how|what should|can i|is there a way)/.test(previous.toLowerCase()));
        let out = answer.replace(/\s+$/, "");
        let checked = false; // the answer made a claim we could verify

        // Key combinations
        const binds = scored.filter(s => s.fact.startsWith("Press "));
        const mentioned = new Set(root.allMatches(root.keyPattern, answer).map(m => root.normKey(m[0])));
        if (binds.length > 0) {
            const keyOf = s => root.normKey(s.fact.split(" ")[1]);
            const bscore = {};
            for (const s of binds) bscore[keyOf(s)] = s.score;
            const topKey = keyOf(binds[0]);
            const named = [...mentioned].filter(k => k in bscore).map(k => bscore[k]);
            if ([...mentioned].some(k => !(k in bscore)))
                return binds[0].fact; // a key the model made up
            if (asked || howTo) {
                // The binding that matches the question best wins over a
                // clearly worse one the model picked.
                const ratio = asked ? 1.2 : 1.5;
                if (named.length > 0 && !mentioned.has(topKey) && bscore[topKey] >= ratio * Math.max(...named))
                    return binds[0].fact;
                if (named.length === 0 && asked)
                    return binds[0].fact;
                if (named.length === 0) {
                    // A how-to a binding clearly answers: the binding is the
                    // answer (the model's own suggestion tends to be invented).
                    if (found.coverage >= 0.4)
                        return binds[0].fact;
                    out += "\n\n" + Translation.tr("Shortcut: %1").arg(binds[0].fact);
                    checked = true;
                }
            }
            checked = checked || named.length > 0;
        } else if (mentioned.size > 0) {
            // Keys named although no binding matches the question.
            return scored.length > 0
                ? Translation.tr("I'm not sure. The closest thing in your configuration: %1").arg(scored[0].fact)
                : Translation.tr("I don't know.");
        }

        // "Is <module> enabled?"
        if (/enabled|\benable|\bactive|\bturned on|\bon this machine|\busing\b/.test(q)) {
            for (const mod of root.data.modules.all) {
                if (!new RegExp(`\\b${root.escapeRe(mod.toLowerCase())}\\b`).test(q)) continue;
                const truth = root.data.modules.enabled.includes(mod);
                if (root.yesNo(answer) !== truth)
                    return truth ? Translation.tr("Yes, %1 is enabled on this machine.").arg(mod)
                                 : Translation.tr("No, %1 is not enabled on this machine.").arg(mod);
                checked = true;
                break;
            }
        }

        // "Is <package> installed?"
        if (/\binstall/.test(q)) {
            for (const pkg of root.data.packages) {
                if (pkg.length <= 2 || !new RegExp(`\\b${root.escapeRe(pkg.toLowerCase())}\\b`).test(q)) continue;
                if (root.yesNo(answer) !== true)
                    return Translation.tr("Yes, %1 is installed.").arg(pkg);
                checked = true;
                break;
            }
        }

        // Setting names and repository files the answer names must exist.
        const notes = [];
        for (const m of root.allMatches(/`?\b([a-z][A-Za-z0-9]*(?:\.[a-z][A-Za-z0-9]*)+)\b`?/g, answer)) {
            const path = m[1];
            if (/\.(nix|md|json|qml|sh|py)$/.test(path)) continue;
            const top = path.split(".")[0];
            if (![...root._settingPaths].some(p => p.startsWith(top + "."))) continue; // not a shell setting
            if (root._settingPaths.has(path) || [...root._settingPaths].some(p => p.startsWith(path + "."))) {
                checked = true;
                continue;
            }
            notes.push(Translation.tr("`%1` is not a setting of this shell.").arg(path));
        }
        for (const m of root.allMatches(/\b((?:profiles|nixosModules|homeManagerModules|customPkgs)\/[\w./-]+)/g, answer)) {
            if (root.knownPath(m[1])) {
                checked = true;
                continue;
            }
            notes.push(Translation.tr("`%1` doesn't look like a file of the configuration.").arg(m[1]));
        }
        if (notes.length > 0)
            out += "\n\n⚠ " + notes.join(" ") + " " + Translation.tr("I may be wrong here: check KEYBINDS.md or the repository.");

        // Nothing verifiable, and the question is only weakly covered by the
        // configuration: don't pass a guess off as an answer.
        if (!checked && notes.length === 0 && found.coverage < 0.45)
            return scored.length > 0
                ? Translation.tr("I'm not sure: this isn't clearly in your configuration. The closest thing in it: %1").arg(scored[0].fact)
                : Translation.tr("I don't know: I couldn't find that in this machine's configuration.");
        return out;
    }
}
