pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common
import qs.modules.common.functions

/**
 * Niri counterpart of HyprlandConfig.
 * Persists shell-managed niri options as JSON (DMS-style) in ~/.config/niri/qssettings/settings.json
 * and generates KDL override fragments next to it. Niri picks them up automatically
 * when the user adds the include lines to config.kdl (niri watches included files).
 */
Singleton {
    id: root

    property alias options: adapter
    property bool ready: false
    property int readWriteDelay: 150

    readonly property string qssettingsDir: FileUtils.trimFileProtocol(`${Directories.config}/niri/qssettings`)
    readonly property string settingsPath: `${qssettingsDir}/settings.json`
    readonly property string shellKdlPath: `${qssettingsDir}/shell.kdl`
    readonly property string outputsKdlPath: `${qssettingsDir}/outputs.kdl`
    readonly property string autostartKdlPath: `${qssettingsDir}/autostart.kdl`
    readonly property string bindsKdlPath: `${qssettingsDir}/binds.kdl`
    // Must go at the END of config.kdl: later includes override earlier sections.
    // binds.kdl is generated by the upcoming Shortcuts page; optional=true means
    // niri won't complain until it exists.
    readonly property string includeLines: 'include optional=true "qssettings/shell.kdl"\ninclude optional=true "qssettings/outputs.kdl"\ninclude optional=true "qssettings/autostart.kdl"\ninclude optional=true "qssettings/binds.kdl"'

    readonly property string generatedHeader: "// ! AUTO-GENERATED by the shell settings app — do not edit, changes will be overwritten\n\n"

    Component.onCompleted: {
        Quickshell.execDetached(["mkdir", "-p", root.qssettingsDir])
    }

    function generateShellKdl() {
        const o = adapter
        let kdl = root.generatedHeader

        kdl += "layout {\n"
        kdl += `    gaps ${o.layout.gaps}\n`
        kdl += `    center-focused-column "${o.layout.centerFocusedColumn}"\n`
        kdl += `    default-column-width { proportion ${o.layout.defaultColumnWidth}; }\n`
        kdl += "    border {\n"
        kdl += `        ${o.decoration.border.enable ? "on" : "off"}\n`
        kdl += `        width ${o.decoration.border.width}\n`
        kdl += "    }\n"
        kdl += "    focus-ring {\n"
        kdl += `        ${o.decoration.focusRing.enable ? "on" : "off"}\n`
        kdl += `        width ${o.decoration.focusRing.width}\n`
        kdl += "    }\n"
        kdl += "    shadow {\n"
        kdl += `        ${o.decoration.shadow.enable ? "on" : "off"}\n`
        kdl += `        softness ${o.decoration.shadow.softness}\n`
        kdl += `        spread ${o.decoration.shadow.spread}\n`
        kdl += "    }\n"
        kdl += "}\n\n"

        if (o.decoration.rounding > 0) {
            kdl += "window-rule {\n"
            kdl += `    geometry-corner-radius ${o.decoration.rounding}\n`
            kdl += "    clip-to-geometry true\n"
            kdl += "}\n\n"
        }

        if (o.decoration.blur.enable) {
            kdl += "blur {\n"
            kdl += `    passes ${o.decoration.blur.passes}\n`
            kdl += `    offset ${o.decoration.blur.offset}\n`
            kdl += `    noise ${o.decoration.blur.noise}\n`
            kdl += `    saturation ${o.decoration.blur.saturation}\n`
            kdl += "}\n\n"
        }

        kdl += "input {\n"
        kdl += "    keyboard {\n"
        kdl += `        xkb { layout "${o.input.kbLayout}"; }\n`
        kdl += `        repeat-delay ${o.input.repeatDelay}\n`
        kdl += `        repeat-rate ${o.input.repeatRate}\n`
        if (o.input.numlock) kdl += "        numlock\n"
        kdl += "    }\n"
        // Pointing device sections are replaced (not merged) by niri includes,
        // so always write them complete
        kdl += "    touchpad {\n"
        if (o.input.touchpad.tap) kdl += "        tap\n"
        if (o.input.touchpad.naturalScroll) kdl += "        natural-scroll\n"
        if (o.input.touchpad.disableWhileTyping) kdl += "        dwt\n"
        kdl += `        scroll-factor ${o.input.touchpad.scrollFactor}\n`
        kdl += `        accel-speed ${o.input.touchpad.accelSpeed}\n`
        kdl += "    }\n"
        kdl += "    mouse {\n"
        if (o.input.mouse.naturalScroll) kdl += "        natural-scroll\n"
        kdl += `        accel-speed ${o.input.mouse.accelSpeed}\n`
        kdl += "    }\n"
        if (o.input.focusFollowsMouse) kdl += "    focus-follows-mouse\n"
        kdl += "}\n\n"

        kdl += "animations {\n"
        if (!o.animations.enable) kdl += "    off\n"
        kdl += `    slowdown ${o.animations.slowdown}\n`
        kdl += "}\n\n"

        kdl += "cursor {\n"
        if (o.cursor.theme !== "") kdl += `    xcursor-theme "${o.cursor.theme}"\n`
        kdl += `    xcursor-size ${o.cursor.size}\n`
        if (o.cursor.hideWhenTyping) kdl += "    hide-when-typing\n"
        kdl += "}\n"

        shellKdlFile.setText(kdl)
    }

    function kdlEscape(str) {
        return String(str).replace(/\\/g, "\\\\").replace(/"/g, '\\"')
    }

    // Autostart entries live in adapter.autostart as {command: string, enabled: bool}.
    // Emitted as `spawn-at-startup "sh" "-c" "<command>"` — spawn-at-startup takes
    // argv (no shell), and wrapping in sh -c keeps pipes/env vars/~ working and is
    // supported by every niri version (unlike spawn-sh-at-startup, 25.08+).
    function generateAutostartKdl() {
        let kdl = root.generatedHeader
        kdl += "// Applied on the next niri start\n"
        for (const entry of (adapter.autostart ?? [])) {
            const cmd = String(entry?.command ?? "").trim()
            if (!entry?.enabled || cmd === "") continue
            kdl += `spawn-at-startup "sh" "-c" "${root.kdlEscape(cmd)}"\n`
        }
        autostartKdlFile.setText(kdl)
    }

    // Keybind overrides live in adapter.bindOverrides as {key, action, title}.
    // binds.kdl is included at the END of config.kdl and in niri the last
    // bind for a key wins, so these shadow the user's own binds per-key
    // without ever touching keybinding.kdl. The action is raw KDL bind
    // syntax (e.g. `spawn "foo"` or `focus-workspace 1`), emitted verbatim.
    function generateBindsKdl() {
        let kdl = root.generatedHeader
        kdl += "binds {\n"
        for (const entry of (adapter.bindOverrides ?? [])) {
            const key = String(entry?.key ?? "").trim()
            const action = String(entry?.action ?? "").trim().replace(/;\s*$/, "")
            // Modifiers + XKB keysym name only — a malformed key would break
            // the whole generated file for niri
            if (!/^[A-Za-z0-9_]+(\+[A-Za-z0-9_]+)*$/.test(key) || action === "") continue
            const title = String(entry?.title ?? "").trim()
            const titleProp = title !== "" ? ` hotkey-overlay-title="${root.kdlEscape(title)}"` : ""
            kdl += `    ${key}${titleProp} { ${action}; }\n`
        }
        kdl += "}\n"
        bindsKdlFile.setText(kdl)
    }

    // monitors: array in MonitorConfigOption shape ({name, currentMode, x, y, scale, transform, disabled, vrr})
    function generateOutputsKdl(monitors) {
        let kdl = root.generatedHeader
        const transformNames = ["normal", "90", "180", "270"]
        for (const m of monitors) {
            kdl += `output "${m.name}" {\n`
            if (m.disabled) {
                kdl += "    off\n}\n\n"
                continue
            }
            const mode = m.currentMode.match(/(\d+)x(\d+)@([\d.]+)/)
            if (mode) kdl += `    mode "${mode[1]}x${mode[2]}@${parseFloat(mode[3]).toFixed(3)}"\n`
            kdl += `    scale ${m.scale}\n`
            if (m.transform) kdl += `    transform "${transformNames[m.transform] ?? "normal"}"\n`
            kdl += `    position x=${m.x} y=${m.y}\n`
            if (m.vrr) kdl += "    variable-refresh-rate\n"
            kdl += "}\n\n"
        }
        outputsKdlFile.setText(kdl)
    }

    Timer {
        id: fileWriteTimer
        interval: root.readWriteDelay
        onTriggered: {
            settingsFileView.writeAdapter()
            root.generateShellKdl()
            root.generateAutostartKdl()
            root.generateBindsKdl()
        }
    }

    FileView {
        id: shellKdlFile
        path: root.shellKdlPath
    }

    FileView {
        id: autostartKdlFile
        path: root.autostartKdlPath
    }

    FileView {
        id: bindsKdlFile
        path: root.bindsKdlPath
    }

    FileView {
        id: outputsKdlFile
        path: root.outputsKdlPath
    }

    FileView {
        id: settingsFileView
        path: root.settingsPath
        watchChanges: true
        onFileChanged: reload()
        onAdapterUpdated: fileWriteTimer.restart()
        onLoaded: root.ready = true
        onLoadFailed: error => {
            if (error == FileViewError.FileNotFound) {
                writeAdapter()
                root.generateShellKdl()
                root.generateAutostartKdl()
                root.generateBindsKdl()
            }
        }

        JsonAdapter {
            id: adapter

            property JsonObject layout: JsonObject {
                property int gaps: 3
                property string centerFocusedColumn: "on-overflow"
                property real defaultColumnWidth: 0.5
            }

            property JsonObject decoration: JsonObject {
                property int rounding: 12
                property JsonObject border: JsonObject {
                    property bool enable: true
                    property int width: 1
                }
                property JsonObject focusRing: JsonObject {
                    property bool enable: true
                    property int width: 2
                }
                property JsonObject shadow: JsonObject {
                    property bool enable: false
                    property int softness: 30
                    property int spread: 5
                }
                property JsonObject blur: JsonObject {
                    property bool enable: true
                    property int passes: 3
                    property real offset: 3.0
                    property real noise: 0.02
                    property real saturation: 1.2
                }
            }

            property JsonObject input: JsonObject {
                property string kbLayout: "us"
                property bool numlock: false
                property int repeatDelay: 600
                property int repeatRate: 25
                property bool focusFollowsMouse: false
                property JsonObject touchpad: JsonObject {
                    property bool tap: true
                    property bool naturalScroll: true
                    property bool disableWhileTyping: false
                    property real scrollFactor: 1.0
                    property real accelSpeed: 0.0
                }
                property JsonObject mouse: JsonObject {
                    property bool naturalScroll: false
                    property real accelSpeed: 0.0
                }
            }

            property JsonObject animations: JsonObject {
                property bool enable: true
                property real slowdown: 1.0
            }

            property JsonObject cursor: JsonObject {
                property string theme: ""
                property int size: 24
                property bool hideWhenTyping: false
            }

            // [{command: string, enabled: bool}] -> qssettings/autostart.kdl
            property list<var> autostart: []

            // [{key: string, action: string, title: string}] -> qssettings/binds.kdl
            property list<var> bindOverrides: []
        }
    }
}
