pragma Singleton
pragma ComponentBehavior: Bound

import qs.modules.common.functions as CF
import qs
import qs.modules.common
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import QtQuick
import qs.services.ai

/**
 * The side panel's chat: the config assistant (answers from this machine's
 * configuration, no AI) and Claude through Claude Code.
 */
Singleton {
    id: root

    property Component aiMessageComponent: AiMessageData {}
    property Component aiModelComponent: AiModel {}
    property ClaudeCodeApiStrategy claudeCodeApiStrategy: ClaudeCodeApiStrategy {}
    readonly property string interfaceRole: "interface"

    signal responseFinished()

    // Without the desktop memory: Claude Code gets that from the desktop MCP
    // server itself.
    property string systemPrompt: {
        let prompt = Config.options?.ai?.systemPrompt ?? "";
        for (let key in root.promptSubstitutions) {
            // prompt = prompt.replaceAll(key, root.promptSubstitutions[key]);
            // QML/JS doesn't support replaceAll, so use split/join
            prompt = prompt.split(key).join(root.promptSubstitutions[key]);
        }
        if (Config.options?.ai?.includeSystemContext ?? true) {
            const machine = systemContextFile.loaded ? systemContextFile.text().trim() : "";
            prompt += "\n\n" + [machine, root.liveShellContext].filter(p => p.length > 0).join("\n\n");
        }
        return prompt;
    }
    // What this machine's Nix configuration sets up (generated by the Home
    // Manager module: modules, keybinds, pinned shell settings, packages).
    FileView {
        id: systemContextFile
        path: `${Directories.shellConfig}/system-context.md`
        watchChanges: true
        onFileChanged: reload()
    }
    // The shell's live settings that matter when asking for help (the Nix file
    // only knows what is pinned; the rest is set from the Settings window).
    readonly property string liveShellContext: {
        const o = Config.options;
        if (!o) return "";
        const widgets = Object.keys(o.background?.widgets ?? {})
            .filter(k => o.background.widgets[k]?.enable === true);
        const lines = [
            "## nixbook-shell live settings (from its Settings window)",
            `- Settings file: ${Directories.shellConfig}/config.json`,
            `- Theme: ${Themes.current}${Themes.variant ? ` (variant ${Themes.variant})` : ""}`,
            `- Bar: ${o.bar?.vertical ? "vertical" : (o.bar?.bottom ? "bottom" : "top")}; left [${(o.bar?.layouts?.leftLayout ?? []).join(", ")}], middle [${(o.bar?.layouts?.middleLayout ?? []).join(", ")}], right [${(o.bar?.layouts?.rightLayout ?? []).join(", ")}]`,
            `- Dock: ${o.dock?.enable ? `on, pinned apps [${(o.dock?.pinnedApps ?? []).join(", ")}]` : "off"}`,
            `- Desktop widgets enabled: ${widgets.length > 0 ? widgets.join(", ") : "none"} (on ${(o.background?.screenList ?? []).length > 0 ? o.background.screenList.join(", ") : "every screen"})`,
            `- Notifications: timeout ${o.notifications?.timeout} ms, one popup per notification: ${o.notifications?.splitPopups}, kept on screen for apps [${(o.notifications?.persistent?.apps ?? []).join(", ")}] / keywords [${(o.notifications?.persistent?.keywords ?? []).join(", ")}]`,
        ];
        return lines.join("\n");
    }
    // property var messages: []
    property var messageIDs: []
    property var messageByID: ({})
    property QtObject tokenCount: QtObject {
        property int input: -1
        property int output: -1
        property int total: -1
    }

    function idForMessage(message) {
        // Generate a unique ID using timestamp and random value
        return Date.now().toString(36) + Math.random().toString(36).substr(2, 8);
    }

    property list<var> defaultPrompts: []
    property list<var> userPrompts: []
    property list<var> promptFiles: [...defaultPrompts, ...userPrompts]
    property list<var> savedChats: []

    property var promptSubstitutions: {
        "{DISTRO}": SystemInfo.distroName,
        "{DATETIME}": `${DateTime.time}, ${DateTime.collapsedCalendarFormat}`,
        "{WINDOWCLASS}": ToplevelManager.activeToplevel?.appId ?? "Unknown",
        "{DE}": `${SystemInfo.desktopEnvironment} (${SystemInfo.windowingSystem})` 
    }

    property string currentTool: Config?.options.ai.tool ?? "functions"
    property var tools: {
        // Claude Code runs its own tools: "functions" gives it the desktop
        // ones (see claudeCodeScript), "none" plain chat.
        "claude-code": {
            "functions": [],
            "none": [],
        }
    }
    property list<var> availableTools: Object.keys(root.tools[models[currentModelId]?.api_format] ?? {})
    property var toolDescriptions: {
        "functions": Translation.tr("See and drive the desktop (the desktop tools)"),
        "none": Translation.tr("Disable tools")
    }

    // "Config assistant" is not a model: it answers from this machine's
    // configuration (services/ConfigAssistant.qml) and never calls anything.
    // First in the list, so it is the default; pick a real model with /model.
    readonly property string configAssistantId: "config-assistant"
    // Claude joins when Claude Code is found (findClaudeCode).
    property var models: ({
        "config-assistant": aiModelComponent.createObject(this, {
            "name": Translation.tr("Config assistant"),
            "icon": "nixos-symbolic",
            "description": Translation.tr("Offline | Answers from this machine's configuration: shortcuts, modules, packages, settings. No AI"),
            "homepage": "",
            "model": "config-assistant",
            "api_format": "config-assistant",
        }),
    })
    property var modelList: Object.keys(root.models)
    // A remembered model that no longer exists (a removed provider, or Claude
    // when Claude Code isn't found) falls back to the first one, the config
    // assistant.
    property var currentModelId: {
        const saved = Persistent.states?.ai?.model;
        return (saved && root.models[saved]) ? saved : modelList[0];
    }
    readonly property bool usingConfigAssistant: root.currentModelId === root.configAssistantId

    property string requestScriptFilePath: `${Directories.aiTemp}/request.sh`
    property string pendingFilePath: ""

    Component.onCompleted: {
        setModel(currentModelId, false, false); // Do necessary setup for model
    }

    function addModel(modelName, data) {
        root.models = Object.assign({}, root.models, {
            [modelName]: aiModelComponent.createObject(this, data)
        });
    }

    Process {
        id: getDefaultPrompts
        running: true
        command: ["ls", "-1", Directories.defaultAiPrompts]
        stdout: StdioCollector {
            onStreamFinished: {
                if (text.length === 0) return;
                root.defaultPrompts = text.split("\n")
                    .filter(fileName => fileName.endsWith(".md") || fileName.endsWith(".txt"))
                    .map(fileName => `${Directories.defaultAiPrompts}/${fileName}`)
            }
        }
    }

    Process {
        id: getUserPrompts
        running: true
        command: ["ls", "-1", Directories.userAiPrompts]
        stdout: StdioCollector {
            onStreamFinished: {
                if (text.length === 0) return;
                root.userPrompts = text.split("\n")
                    .filter(fileName => fileName.endsWith(".md") || fileName.endsWith(".txt"))
                    .map(fileName => `${Directories.userAiPrompts}/${fileName}`)
            }
        }
    }

    Process {
        id: getSavedChats
        running: true
        command: ["ls", "-1", Directories.aiChats]
        stdout: StdioCollector {
            onStreamFinished: {
                if (text.length === 0) return;
                root.savedChats = text.split("\n")
                    .filter(fileName => fileName.endsWith(".json"))
                    .map(fileName => `${Directories.aiChats}/${fileName}`)
            }
        }
    }

    // Desktop control (scripts/desktop-mcp.py, `nixbook-desktop-mcp`): the
    // same tools and guardrails as the MCP server other agents use, given to
    // Claude Code in the "functions" tool set when the server has any.
    readonly property string desktopMcpCommand: "nixbook-desktop-mcp"
    property var desktopTools: []

    Process {
        id: getDesktopTools
        running: true
        command: [root.desktopMcpCommand, "tools"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    const tools = JSON.parse(text);
                    if (Array.isArray(tools)) root.desktopTools = tools;
                } catch (e) {
                    console.log("[Ai] Desktop tools unavailable:", e);
                }
            }
        }
    }

    // Claude through Claude Code (`claude -p`): no API key, the user's own
    // Claude login. Offered as a model when `claude` is found. Each message
    // runs Claude Code once, resuming the session of the previous one; it
    // gets the desktop tools (the desktop MCP server, whose guardrails, pause
    // and memory apply), Config ai.claudeCode.allowedTools and, with
    // ai.claudeCode.connectors, the user's claude.ai connectors; nothing else.
    property string claudeCodePath: ""
    property string claudeSessionId: ""
    // Settings > Desktop agents can change where Claude Code is: look again.
    readonly property string claudeCodeCommandSetting: Config.options?.ai?.claudeCode?.command ?? ""
    onClaudeCodeCommandSettingChanged: claudeCodeRelocate.restart()
    Timer {
        id: claudeCodeRelocate
        interval: 800
        onTriggered: if (Config.ready && Config.options.policies.ai !== 2) findClaudeCode.running = true
    }

    Process {
        id: findClaudeCode
        running: Config.ready && Config.options.policies.ai !== 2
        command: ["bash", "-c", `for c in "$1" "$(command -v claude)" "$HOME/.local/bin/claude" "$HOME/.nix-profile/bin/claude" "/etc/profiles/per-user/$USER/bin/claude" /run/current-system/sw/bin/claude; do [ -n "$c" ] && [ -x "$c" ] && { echo "$c"; exit 0; }; done; exit 1`,
            "find-claude", Config.options.ai.claudeCode.command]
        stdout: StdioCollector {
            onStreamFinished: {
                const path = text.trim();
                root.claudeCodePath = path;
                if (path.length > 0 && root.claudeConnectorsSetting) listClaudeConnectors.running = true;
                if (path.length === 0 || root.models["claude"]) return;
                root.addModel("claude", {
                    "name": "Claude",
                    "icon": "spark-symbolic",
                    "description": Translation.tr("Online | Anthropic's Claude through Claude Code, on your Claude account (no API key) | Can see and drive the desktop"),
                    "homepage": "https://claude.com/claude-code",
                    "model": "claude-code", // the model itself: ai.claudeCode.model
                    "api_format": "claude-code",
                });
                root.modelList = Object.keys(root.models);
            }
        }
    }

    // The claude.ai connectors (Gmail, Calendar, Drive…) of the user's Claude
    // account, as permission rules: `claude mcp list` names them "claude.ai
    // Gmail", their tools are mcp__claude_ai_Gmail__*. Claude Code takes no
    // wildcard over servers, so each one is allowed by name.
    property list<string> claudeConnectors: []
    readonly property bool claudeConnectorsSetting: Config.options?.ai?.claudeCode?.connectors ?? false
    onClaudeConnectorsSettingChanged: if (claudeConnectorsSetting && claudeCodePath.length > 0) listClaudeConnectors.running = true
    Process {
        id: listClaudeConnectors
        command: [root.claudeCodePath, "mcp", "list"]
        workingDirectory: Quickshell.env("HOME")
        stdout: StdioCollector {
            onStreamFinished: {
                root.claudeConnectors = text.split("\n")
                    .map(l => /^(claude\.ai [^:]+):/.exec(l.trim()))
                    .filter(m => m)
                    .map(m => "mcp__" + m[1].replace(/[^A-Za-z0-9_-]/g, "_"));
            }
        }
    }

    function claudeCodeScript(model, messages, attachedFile) {
        const q = s => `'${CF.StringUtils.shellSingleQuoteEscape(String(s))}'`;
        const turns = messages.filter(m => (m.role === "user" || m.role === "assistant") && !m.functionName);
        const last = turns[turns.length - 1];
        let prompt = last?.role === "user" ? last.rawContent : "";
        if (root.claudeSessionId.length === 0 && turns.length > 1) {
            // A new session for a chat that already has turns (another model,
            // a loaded chat, a regenerated answer): the chat so far, as context.
            let earlier = turns.slice(0, -1).map(m => `${m.role === "user" ? "User" : "Assistant"}: ${m.rawContent}`).join("\n\n");
            if (earlier.length > 8000) earlier = "…" + earlier.slice(-8000);
            prompt = `Earlier in this conversation:\n\n${earlier}\n\nThe user now says:\n\n${prompt}`;
        }
        const attached = attachedFile && attachedFile.length > 0 && attachedFile.startsWith("/") ? attachedFile : "";
        if (attached.length > 0)
            prompt += `\n\n(Attached file: ${attached}; read it with the Read tool.)`;

        // No access to the user's files but the folders they allow
        // (ai.allowedFolders: working directories, readable without asking)
        // and a file they attach (that file only). Claude Code runs in an
        // empty directory of its own, with the user's own login and
        // ~/.claude settings (their permission rules apply too: a bare
        // "Read" allow there opens every path while file tools are loaded),
        // and every other read is denied (-p can't ask). No folder, no
        // attachment: no file tools at all (not loaded, and denied: a deny
        // beats any allow rule).
        const fileTools = ["Read", "Glob", "Grep"];
        const home = Quickshell.env("HOME");
        const folders = (Config.options.ai.allowedFolders ?? [])
            .map(f => String(f).trim())
            .map(f => f === "~" ? home : f.startsWith("~/") ? `${home}/${f.slice(2)}` : f)
            .filter(f => f.startsWith("/"));
        const readTools = folders.length > 0 ? ["Read", "Glob", "Grep"] : attached.length > 0 ? ["Read"] : [];
        const configured = (Config.options.ai.claudeCode.allowedTools ?? [])
            .filter(t => !fileTools.some(f => t === f || t.startsWith(`${f}(`)));
        const desktop = root.currentTool !== "none" && root.desktopTools.length > 0;
        const connectors = root.claudeConnectorsSetting;
        const allowed = [...(desktop ? ["mcp__desktop"] : []), ...configured,
            ...(attached.length > 0 ? [`Read(/${attached})`] : []),
            ...(connectors ? root.claudeConnectors : [])];
        const system = root.systemPrompt
            + "\n\nYou are answering in the desktop shell's side panel: keep answers short."
            + (desktop ? " You can see and drive the user's desktop with the desktop tools." : "")
            + (folders.length > 0 ? ` You may read files in these folders only: ${folders.join(", ")}.`
                : " You have no access to the user's files (they can allow folders in Settings > Desktop agents).");
        // --strict-mcp-config leaves out every MCP server but the desktop one,
        // claude.ai connectors included: dropped when they are wanted.
        let args = ["-p", "--output-format", "stream-json", "--verbose", "--include-partial-messages",
            ...(connectors ? [] : ["--strict-mcp-config"]), "--append-system-prompt", system,
            "--disallowedTools", "Bash", "Edit", "Write", "NotebookEdit", ...fileTools.filter(t => !readTools.includes(t))];
        for (const folder of folders) args.push("--add-dir", folder);
        // The message tells the desktop MCP server what the task is: its
        // memory digest then carries the notes about it, the rest by topic.
        const task = (last?.role === "user" ? last.rawContent : "").slice(0, 500);
        if (desktop)
            args.push("--mcp-config", JSON.stringify({ mcpServers: { desktop: {
                command: root.desktopMcpCommand,
                env: { NIXBOOK_DESKTOP_MCP_QUERY: task },
            } } }));
        // Only the allowed built-in tools are loaded at all: Claude Code's
        // full set would double the context of every message.
        // With the connectors, ToolSearch too: their tools stay deferred
        // behind it (without it they all load, ~130k tokens a message).
        const builtins = [...configured, ...readTools, ...(connectors ? ["ToolSearch"] : [])];
        args.push("--tools", ...(builtins.length > 0 ? builtins : [""]));
        if (allowed.length > 0) args.push("--allowedTools", ...allowed);
        const claudeModel = Config.options.ai.claudeCode.model ?? "";
        if (claudeModel.length > 0) args.push("--model", claudeModel);
        if (root.claudeSessionId.length > 0) args.push("--resume", root.claudeSessionId);
        // The desktop tools loaded up front: Claude Code otherwise defers MCP
        // tools behind a ToolSearch call, one more round trip per session.
        // Not with the connectors: hundreds of tools would fill every message.
        // The message on stdin: never read as an option, whatever it starts with.
        return `workdir="\${XDG_DATA_HOME:-$HOME/.local/share}/nixbook-shell/assistant"\n`
            + `mkdir -p "$workdir" && cd "$workdir" || exit 1\n${connectors ? "" : "export ENABLE_TOOL_SEARCH=false\n"}`
            + `exec ${q(root.claudeCodePath)} ${args.map(q).join(" ")} < <(printf '%s' ${q(prompt)})\n`;
    }

    FileView {
        id: promptLoader
        watchChanges: false;
        onLoadedChanged: {
            if (!promptLoader.loaded) return;
            Config.options.ai.systemPrompt = promptLoader.text();
            root.addMessage(Translation.tr("Loaded the following system prompt\n\n---\n\n%1").arg(Config.options.ai.systemPrompt), root.interfaceRole);
        }
    }

    function printPrompt() {
        root.addMessage(Translation.tr("The current system prompt is\n\n---\n\n%1").arg(Config.options.ai.systemPrompt), root.interfaceRole);
    }

    function loadPrompt(filePath) {
        promptLoader.path = "" // Unload
        promptLoader.path = filePath; // Load
        promptLoader.reload();
    }

    function addMessage(message, role) {
        if (message.length === 0) return;
        const aiMessage = aiMessageComponent.createObject(root, {
            "role": role,
            "content": message,
            "rawContent": message,
            "thinking": false,
            "done": true,
        });
        const id = idForMessage(aiMessage);
        root.messageIDs = [...root.messageIDs, id];
        root.messageByID[id] = aiMessage;
    }

    function removeMessage(index) {
        if (index < 0 || index >= messageIDs.length) return;
        const id = root.messageIDs[index];
        root.messageIDs.splice(index, 1);
        root.messageIDs = [...root.messageIDs];
        delete root.messageByID[id];
    }

    function getModel() {
        return models[currentModelId];
    }

    function setModel(modelId, feedback = true, setPersistentState = true) {
        if (!modelId) modelId = ""
        modelId = modelId.toLowerCase()
        if (modelList.indexOf(modelId) !== -1) {
            const model = models[modelId]
            // See if policy prevents online models
            if (Config.options.policies.ai === 2 && model.api_format === "claude-code") {
                root.addMessage(
                    Translation.tr("Online models disallowed\n\nControlled by `policies.ai` config option"),
                    root.interfaceRole
                );
                return;
            }
            if (setPersistentState) Persistent.states.ai.model = modelId;
            if (feedback) root.addMessage(Translation.tr("Model set to %1").arg(model.name), root.interfaceRole);
        } else {
            if (feedback) root.addMessage(Translation.tr("Invalid model. Supported: \n```\n") + modelList.join("\n```\n```\n"), Ai.interfaceRole) + "\n```"
        }
    }

    function setTool(tool) {
        if (!root.tools[models[currentModelId]?.api_format] || !(tool in root.tools[models[currentModelId]?.api_format])) {
            root.addMessage(Translation.tr("Invalid tool. Supported tools:\n- %1").arg(root.availableTools.join("\n- ")), root.interfaceRole);
            return false;
        }
        Config.options.ai.tool = tool;
        return true;
    }
    
    function clearMessages() {
        root.claudeSessionId = "";
        root.messageIDs = [];
        root.messageByID = ({});
        root.tokenCount.input = -1;
        root.tokenCount.output = -1;
        root.tokenCount.total = -1;
    }

    FileView {
        id: requesterScriptFile
        blockWrites: true
    }

    Process {
        id: requester
        property list<string> baseCommand: ["bash"]
        property AiMessageData message
        property AiMessageData activeMessage
        property bool restartPending: false

        function markDone() {
            if (!requester.activeMessage || requester.activeMessage.done) return;
            requester.activeMessage.done = true;
            requester.activeMessage.thinking = false;
            root.saveChat("lastSession")
            root.responseFinished()
        }

        function makeRequest() {
            const model = models[currentModelId];

            // The config assistant: answered here from the configuration, no request.
            if (root.usingConfigAssistant) {
                const turns = root.messageIDs.map(id => root.messageByID[id]).filter(m => m?.role === "user");
                const question = turns[turns.length - 1]?.rawContent ?? "";
                const previous = turns[turns.length - 2]?.rawContent ?? "";
                let answer = Translation.tr("The configuration facts aren't loaded (~/.config/nixbook-shell/system-facts.json, generated by the Home Manager module).");
                try {
                    if (ConfigAssistant.ready) answer = ConfigAssistant.answer(question, previous);
                } catch (e) {
                    console.warn("[Ai] ConfigAssistant.answer failed:", e);
                }
                const reply = root.aiMessageComponent.createObject(root, {
                    "role": "assistant", "model": currentModelId,
                    "content": answer, "rawContent": answer, "thinking": false, "done": true,
                });
                const replyId = idForMessage(reply);
                root.messageIDs = [...root.messageIDs, replyId];
                root.messageByID[replyId] = reply;
                root.saveChat("lastSession");
                root.responseFinished();
                return;
            }

            const messageArray = root.messageIDs.map(id => root.messageByID[id]);
            const filteredMessageArray = messageArray.filter(message => message.role !== Ai.interfaceRole);
            root.claudeCodeApiStrategy.reset();

            /* Create local message object */
            requester.message = root.aiMessageComponent.createObject(root, {
                "role": "assistant",
                "model": currentModelId,
                "content": "",
                "rawContent": "",
                "thinking": true,
                "done": false,
            });
            const id = idForMessage(requester.message);
            root.messageIDs = [...root.messageIDs, id];
            root.messageByID[id] = requester.message;

            const attachedFile = root.pendingFilePath;
            if (attachedFile && attachedFile.length > 0) {
                requester.message.localFilePath = attachedFile;
                root.pendingFilePath = ""
            }

            /* Send the request */
            const scriptContent = "#!/usr/bin/env bash\n" + root.claudeCodeScript(model, filteredMessageArray, attachedFile);
            const shellScriptPath = CF.FileUtils.trimFileProtocol(root.requestScriptFilePath)
            requesterScriptFile.path = Qt.resolvedUrl(shellScriptPath)
            requesterScriptFile.setText(scriptContent)
            if (requester.running) {
                if (requester.activeMessage && requester.activeMessage !== requester.message && !requester.activeMessage.done) {
                    requester.activeMessage.done = true;
                    requester.activeMessage.thinking = false;
                }
                requester.restartPending = true;
                requester.signal(15);
            } else {
                requester.spawn();
            }
        }

        function spawn() {
            requester.activeMessage = requester.message;
            requester.command = baseCommand.concat([CF.FileUtils.trimFileProtocol(root.requestScriptFilePath)]);
            requester.running = true;
        }

        stdout: SplitParser {
            onRead: data => {
                if (data.length === 0 || !requester.activeMessage) return;
                if (requester.activeMessage.thinking) requester.activeMessage.thinking = false;
                // console.log("[Ai] Raw response line: ", data);

                // Handle response line
                try {
                    const result = root.claudeCodeApiStrategy.parseResponseLine(data, requester.activeMessage);
                    // console.log("[Ai] Parsed response result: ", JSON.stringify(result, null, 2));

                    if (result.sessionId) root.claudeSessionId = result.sessionId;
                    if (result.tokenUsage) {
                        root.tokenCount.input = result.tokenUsage.input;
                        root.tokenCount.output = result.tokenUsage.output;
                        root.tokenCount.total = result.tokenUsage.total;
                    }
                    if (result.finished) {
                        requester.markDone();
                    }
                    
                } catch (e) {
                    console.log("[AI] Could not parse response: ", e);
                    requester.activeMessage.rawContent += data;
                    requester.activeMessage.content += data;
                }
            }
        }

        onExited: (exitCode, exitStatus) => {
            if (requester.activeMessage && !requester.activeMessage.done) {
                root.claudeCodeApiStrategy.onRequestFinished(requester.activeMessage);
                requester.markDone();
            }
            if (requester.restartPending) {
                requester.restartPending = false;
                requester.spawn();
            }
        }
    }

    readonly property bool responding: requester.running

    // Stops the answer being written (and, for Claude, what it is doing).
    function stopResponse() {
        if (!requester.running) return;
        requester.restartPending = false;
        requester.signal(15);
    }

    function sendUserMessage(message) {
        if (message.length === 0) return;
        root.addMessage(message, "user");
        requester.makeRequest();
    }

    function attachFile(filePath: string) {
        root.pendingFilePath = CF.FileUtils.trimFileProtocol(filePath);
    }

    function regenerate(messageIndex) {
        if (messageIndex < 0 || messageIndex >= messageIDs.length) return;
        const id = root.messageIDs[messageIndex];
        const message = root.messageByID[id];
        if (message.role !== "assistant") return;
        // Remove all messages after this one
        for (let i = root.messageIDs.length - 1; i >= messageIndex; i--) {
            root.removeMessage(i);
        }
        // Claude Code's session still holds the removed answer: start a new
        // one, with the chat so far as context.
        root.claudeSessionId = "";
        requester.makeRequest();
    }

    function chatToJson() {
        return root.messageIDs.map(id => {
            const message = root.messageByID[id]
            return ({
                "role": message.role,
                "rawContent": message.rawContent,
                "fileMimeType": message.fileMimeType,
                "fileUri": message.fileUri,
                "localFilePath": message.localFilePath,
                "model": message.model,
                "thinking": false,
                "done": true,
                "annotations": message.annotations,
                "annotationSources": message.annotationSources,
                "functionName": message.functionName,
                "functionCall": message.functionCall,
                "functionResponse": message.functionResponse,
                "visibleToUser": message.visibleToUser,
            })
        })
    }

    FileView {
        id: chatSaveFile
        property string chatName: ""
        path: chatName.length > 0 ? `${Directories.aiChats}/${chatName}.json` : ""
        blockLoading: true // Prevent race conditions
    }

    /**
     * Saves chat to a JSON list of message objects.
     * @param chatName name of the chat
     */
    function saveChat(chatName) {
        chatSaveFile.chatName = chatName.trim()
        const saveContent = JSON.stringify(root.chatToJson())
        chatSaveFile.setText(saveContent)
        getSavedChats.running = true;
    }

    /**
     * Loads chat from a JSON list of message objects.
     * @param chatName name of the chat
     */
    function loadChat(chatName) {
        root.claudeSessionId = "";
        try {
            chatSaveFile.chatName = chatName.trim()
            chatSaveFile.reload()
            const saveContent = chatSaveFile.text()
            // console.log(saveContent)
            const saveData = JSON.parse(saveContent)
            root.clearMessages()
            root.messageIDs = saveData.map((_, i) => {
                return i
            })
            // console.log(JSON.stringify(messageIDs))
            for (let i = 0; i < saveData.length; i++) {
                const message = saveData[i];
                root.messageByID[i] = root.aiMessageComponent.createObject(root, {
                    "role": message.role,
                    "rawContent": message.rawContent,
                    "content": message.rawContent,
                    "fileMimeType": message.fileMimeType,
                    "fileUri": message.fileUri,
                    "localFilePath": message.localFilePath,
                    "model": message.model,
                    "thinking": message.thinking,
                    "done": message.done,
                    "annotations": message.annotations,
                    "annotationSources": message.annotationSources,
                    "functionName": message.functionName,
                    "functionCall": message.functionCall,
                    "functionResponse": message.functionResponse,
                    "visibleToUser": message.visibleToUser,
                });
            }
        } catch (e) {
            console.log("[AI] Could not load chat: ", e);
        } finally {
            getSavedChats.running = true;
        }
    }
}
