pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common

/**
 * The config assistant: the chat's built-in "Config assistant" entry
 * (Ai.configAssistantId). No AI — every answer comes from this machine's
 * configuration, instantly and exactly. To chat with a model instead
 * (Gemini, an Ollama you run), pick it with /model.
 *
 * Understanding: the question's language is detected (English, French,
 * German, Vietnamese — accents optional), and a lexicon maps its words onto
 * the English vocabulary of the facts (prefix match for inflections).
 * Retrieval: keyword overlap weighted by rarity (IDF), light stemming,
 * synonyms; templated facts are indexed on their distinctive part only; the
 * previous question counts at half weight, for follow-ups.
 *
 * Answers (`answer`): greetings and help; listings (all shortcuts,
 * shortcuts about X, Neovim keymaps, enabled modules, settings set in Nix,
 * packages); "what does <leader>ff do in vim?"; "is
 * <module> enabled?"; "is <package> installed?"; "what does <key> do?"; a
 * request a keybinding answers (key + description) — all in `quickReply`;
 * otherwise the closest facts, or "I don't know" with tips when the
 * configuration doesn't cover the question.
 *
 * Facts: ~/.config/nixbook-shell/system-facts.json, generated by the Home
 * Manager module (customPkgs/nixbook-shell/scripts/assistant-facts.py), in
 * all four languages.
 */
Singleton {
    id: root

    readonly property bool ready: root.data !== null
    property var data: null
    property var _factWords: []
    property var _idf: ({})
    property real _maxIdf: 1
    property var _settingPaths: new Set()

    FileView {
        id: factsFile
        path: `${Directories.shellConfig}/system-facts.json`
        watchChanges: true
        onFileChanged: reload()
        onLoaded: root.load(factsFile.text())
        onLoadFailed: root.data = null
    }

    // ------------------------------------------------------------ texts
    readonly property var strings: ({
        en: {
            hi: "Hi!", welcome: "You're welcome!",
            capabilities: "I answer questions about this machine's configuration: the system (version, kernel, services), how to update or roll it back, shortcuts, enabled modules, installed packages, and where to change a setting.",
            sysInfo: "About this machine (%1):", toggleYes: "Yes: %1 is enabled.", toggleNo: "No: %1 is not enabled.", enabledToggles: "Enabled on %1 (option sets with enable = true):",
            tips: "Name the thing, e.g. “shortcut for the launcher”, “is tailscale enabled?”, “all shortcuts”.",
            dontKnow: "I don't know: that isn't in this machine's configuration.",
            notSure: "No exact match in this machine's configuration. The closest things in it:",
            allShortcuts: "All keyboard shortcuts (%1, Mod = Super key):",
            matching: "Shortcuts matching your question (Mod = Super key):",
            enabledModules: "Enabled modules on %1:", notEnabled: "Available but not enabled:",
            pinned: "Shell settings set in Nix (locked in the Settings window):",
            packages: "Installed packages (%1):",
            modYes: "Yes, %1 is enabled on this machine.", modNo: "No, %1 is not enabled on this machine.",
            pkgYes: "Yes, %1 is installed.",
            pkgKnown: "%1 is installed on this machine (I only know its configuration, not how to use the tool).",
            nvimShortcuts: "Neovim keymaps (%1, <leader> = %2):", nvimMatching: "Neovim keymaps matching your question (<leader> = %1):", nvimNone: "No Neovim keymaps are configured on this machine.", nvimUnbound: "%1 isn't mapped in Neovim on this machine.",
            also: "Also:", shortcut: "Shortcut:", unbound: "%1 isn't bound to anything on this machine.",
        },
        fr: {
            hi: "Salut !", welcome: "De rien !",
            capabilities: "Je réponds aux questions sur la configuration de cette machine : le système (version, noyau, services), comment le mettre à jour ou revenir en arrière, raccourcis, modules activés, paquets installés, et où changer un réglage.",
            sysInfo: "À propos de cette machine (%1) :", toggleYes: "Oui : %1 est activé.", toggleNo: "Non : %1 n'est pas activé.", enabledToggles: "Activé sur %1 (options avec enable = true) :",
            tips: "Nommez la chose, par ex. « raccourci du lanceur », « tailscale est activé ? », « tous les raccourcis ».",
            dontKnow: "Je ne sais pas : ce n'est pas dans la configuration de cette machine.",
            notSure: "Pas de correspondance exacte dans la configuration de cette machine. Le plus proche :",
            allShortcuts: "Tous les raccourcis clavier (%1, Mod = touche Super) :",
            matching: "Raccourcis correspondant à votre question (Mod = touche Super) :",
            enabledModules: "Modules activés sur %1 :", notEnabled: "Disponibles mais non activés :",
            pinned: "Réglages du shell définis dans Nix (verrouillés dans les paramètres) :",
            packages: "Paquets installés (%1) :",
            modYes: "Oui, %1 est activé sur cette machine.", modNo: "Non, %1 n'est pas activé sur cette machine.",
            pkgYes: "Oui, %1 est installé.",
            pkgKnown: "%1 est installé sur cette machine (je ne connais que sa configuration, pas l'utilisation de l'outil).",
            nvimShortcuts: "Raccourcis Neovim (%1, <leader> = %2) :", nvimMatching: "Raccourcis Neovim correspondant à votre question (<leader> = %1) :", nvimNone: "Aucun raccourci Neovim n'est configuré sur cette machine.", nvimUnbound: "%1 n'est associé à rien dans Neovim sur cette machine.",
            also: "Aussi :", shortcut: "Raccourci :", unbound: "%1 n'est associé à rien sur cette machine.",
        },
        de: {
            hi: "Hallo!", welcome: "Gern geschehen!",
            capabilities: "Ich beantworte Fragen zur Konfiguration dieses Rechners: das System (Version, Kernel, Dienste), wie man es aktualisiert oder zurücksetzt, Tastenkürzel, aktivierte Module, installierte Pakete und wo man eine Einstellung ändert.",
            sysInfo: "Über diesen Rechner (%1):", toggleYes: "Ja: %1 ist aktiviert.", toggleNo: "Nein: %1 ist nicht aktiviert.", enabledToggles: "Aktiviert auf %1 (Optionen mit enable = true):",
            tips: "Nenne die Sache, z. B. „Tastenkürzel für den Starter“, „ist tailscale aktiviert?“, „alle Tastenkürzel“.",
            dontKnow: "Weiß ich nicht: Das steht nicht in der Konfiguration dieses Rechners.",
            notSure: "Keine genaue Entsprechung in der Konfiguration dieses Rechners. Am nächsten kommen:",
            allShortcuts: "Alle Tastenkürzel (%1, Mod = Super-Taste):",
            matching: "Passende Tastenkürzel (Mod = Super-Taste):",
            enabledModules: "Aktivierte Module auf %1:", notEnabled: "Verfügbar, aber nicht aktiviert:",
            pinned: "In Nix gesetzte Shell-Einstellungen (in den Einstellungen gesperrt):",
            packages: "Installierte Pakete (%1):",
            modYes: "Ja, %1 ist auf diesem Rechner aktiviert.", modNo: "Nein, %1 ist auf diesem Rechner nicht aktiviert.",
            pkgYes: "Ja, %1 ist installiert.",
            pkgKnown: "%1 ist auf diesem Rechner installiert (ich kenne nur die Konfiguration, nicht die Bedienung des Programms).",
            nvimShortcuts: "Neovim-Tastenbelegungen (%1, <leader> = %2):", nvimMatching: "Passende Neovim-Tastenbelegungen (<leader> = %1):", nvimNone: "Auf diesem Rechner sind keine Neovim-Tastenbelegungen konfiguriert.", nvimUnbound: "%1 ist in Neovim auf diesem Rechner mit nichts belegt.",
            also: "Auch:", shortcut: "Tastenkürzel:", unbound: "%1 ist auf diesem Rechner mit nichts belegt.",
        },
        vi: {
            hi: "Xin chào!", welcome: "Không có gì!",
            capabilities: "Tôi trả lời câu hỏi về cấu hình của máy này: hệ thống (phiên bản, kernel, dịch vụ), cách cập nhật hoặc quay lại, phím tắt, module đang bật, gói đã cài, và nơi đổi một thiết lập.",
            sysInfo: "Về máy này (%1):", toggleYes: "Có: %1 đang được bật.", toggleNo: "Không: %1 không được bật.", enabledToggles: "Đang bật trên %1 (các tùy chọn có enable = true):",
            tips: "Hãy nêu rõ, ví dụ: “phím tắt mở trình khởi chạy”, “tailscale có bật không?”, “tất cả phím tắt”.",
            dontKnow: "Tôi không biết: điều này không có trong cấu hình của máy.",
            notSure: "Không có kết quả khớp chính xác trong cấu hình của máy. Gần nhất là:",
            allShortcuts: "Tất cả phím tắt (%1, Mod = phím Super):",
            matching: "Các phím tắt phù hợp (Mod = phím Super):",
            enabledModules: "Module đang bật trên %1:", notEnabled: "Có sẵn nhưng chưa bật:",
            pinned: "Thiết lập shell đặt trong Nix (bị khóa trong cửa sổ cài đặt):",
            packages: "Các gói đã cài (%1):",
            modYes: "Có, %1 đang được bật trên máy này.", modNo: "Không, %1 không được bật trên máy này.",
            pkgYes: "Có, %1 đã được cài.",
            pkgKnown: "%1 đã được cài trên máy này (tôi chỉ biết cấu hình, không biết cách dùng công cụ).",
            nvimShortcuts: "Phím tắt Neovim (%1, <leader> = %2):", nvimMatching: "Các phím tắt Neovim phù hợp (<leader> = %1):", nvimNone: "Máy này không cấu hình phím tắt Neovim nào.", nvimUnbound: "%1 không được gán trong Neovim trên máy này.",
            also: "Ngoài ra:", shortcut: "Phím tắt:", unbound: "%1 không được gán cho chức năng nào trên máy này.",
        }
    })
    // /help and the chat's help tooltip: questions answered right away from
    // the configuration (quickReply). A third element names what an entry
    // needs ("nvim": Neovim keymaps, "os": system facts, "howto": how-tos).
    readonly property var helpExamples: ({
        en: { title: "Answered instantly from your configuration (no model):", more: "No AI here: to chat with a model (Gemini, Ollama…), pick one with /model.", items: [
            ["Find a shortcut", "shortcut for the launcher · how do I lock the screen"],
            ["What a key does", "what does Mod+R do?"],
            ["List shortcuts", "all shortcuts · shortcuts for workspaces"],
            ["Neovim keymaps", "all vim shortcuts · vim shortcut to find files · what does <leader>ff do in vim?", "nvim"],
            ["Your system", "which kernel? · is bluetooth enabled? · keyboard layout · system info", "os"],
            ["How do I…", "how do I update the system? · how do I roll back? · free disk space", "howto"],
            ["Modules", "is tailscale enabled? · which modules are enabled"],
            ["Packages", "is firefox installed? · which packages are installed"],
            ["Shell settings", "settings set in Nix"]] },
        fr: { title: "Réponse immédiate depuis votre configuration (sans modèle) :", more: "Pas d'IA ici : pour discuter avec un modèle (Gemini, Ollama…), choisissez-le avec /model.", items: [
            ["Trouver un raccourci", "raccourci pour le lanceur · comment verrouiller l'écran"],
            ["Ce que fait une touche", "que fait Mod+R ?"],
            ["Lister les raccourcis", "tous les raccourcis · raccourcis des espaces de travail"],
            ["Raccourcis Neovim", "tous les raccourcis vim · raccourci vim pour chercher des fichiers · que fait <leader>ff dans vim ?", "nvim"],
            ["Votre système", "quel noyau ? · le bluetooth est activé ? · disposition du clavier · infos système", "os"],
            ["Comment faire…", "comment mettre à jour le système ? · comment revenir en arrière ? · libérer de l'espace disque", "howto"],
            ["Modules", "tailscale est activé ? · quels modules sont activés"],
            ["Paquets", "firefox est installé ? · quels paquets sont installés"],
            ["Réglages du shell", "réglages définis dans Nix"]] },
        de: { title: "Sofort aus deiner Konfiguration beantwortet (ohne Modell):", more: "Keine KI hier: Um mit einem Modell (Gemini, Ollama…) zu chatten, wähle es mit /model.", items: [
            ["Tastenkürzel finden", "Tastenkürzel für den Starter · wie sperre ich den Bildschirm"],
            ["Was eine Taste macht", "was macht Mod+R?"],
            ["Kürzel auflisten", "alle Tastenkürzel · Kürzel für Arbeitsbereiche"],
            ["Neovim-Belegungen", "alle vim-Tastenkürzel · vim-Kürzel zum Dateien suchen · was macht <leader>ff in vim?", "nvim"],
            ["Dein System", "welcher Kernel? · ist Bluetooth aktiviert? · Tastaturlayout · Systeminfo", "os"],
            ["Wie mache ich…", "wie aktualisiere ich das System? · wie setze ich zurück? · Speicherplatz freigeben", "howto"],
            ["Module", "ist tailscale aktiviert? · welche Module sind aktiv"],
            ["Pakete", "ist firefox installiert? · welche Pakete sind installiert"],
            ["Shell-Einstellungen", "Einstellungen in Nix"]] },
        vi: { title: "Trả lời ngay từ cấu hình của bạn (không cần mô hình):", more: "Không dùng AI ở đây: để trò chuyện với mô hình (Gemini, Ollama…), chọn bằng /model.", items: [
            ["Tìm phím tắt", "phím tắt mở trình khởi chạy · làm sao khóa màn hình"],
            ["Phím làm gì", "Mod+R để làm gì?"],
            ["Liệt kê phím tắt", "tất cả phím tắt · phím tắt cho không gian làm việc"],
            ["Phím tắt Neovim", "tất cả phím tắt vim · phím tắt vim tìm tệp · <leader>ff trong vim làm gì?", "nvim"],
            ["Hệ thống", "kernel nào? · bluetooth có bật không? · bố cục bàn phím · thông tin hệ thống", "os"],
            ["Làm sao để…", "làm sao cập nhật hệ thống? · làm sao quay lại? · giải phóng dung lượng đĩa", "howto"],
            ["Module", "tailscale có bật không? · những module nào được bật"],
            ["Gói phần mềm", "firefox đã cài chưa? · những gói nào đã cài"],
            ["Cài đặt shell", "cài đặt trong Nix"]] }
    })
    // The UI language's help, "en" when it isn't one of the four.
    function uiLang() {
        const code = Qt.locale().name.slice(0, 2);
        return root.helpExamples[code] ? code : "en";
    }
    // Markdown for the chat (/help) or plain lines for a tooltip.
    function helpText(lang = root.uiLang(), plain = false) {
        const h = root.helpExamples[lang] ?? root.helpExamples.en;
        // The Neovim line only where there are Neovim keymaps to ask about.
        const kinds = root.data?.kinds ?? [];
        const has = { nvim: (root.data?.nvim?.keymaps?.length ?? 0) > 0, os: kinds.includes("os"),
            howto: kinds.some(k => k.startsWith("howto:")) };
        const items = h.items.filter(([, , needs]) => !needs || has[needs]);
        const lines = items.map(([what, ex]) => plain ? `• ${what}: ${ex}` : `- **${what}**: “${ex.split(" · ").join("”, “")}”`);
        const text = `${plain ? h.title : `**${h.title}**`}\n${lines.join("\n")}\n${plain ? "" : "\n"}${h.more}\nEnglish · Français · Deutsch · Tiếng Việt`;
        return plain ? text : root.codeKeys(text);
    }

    function tr(lang, key, arg, arg2) {
        const s = (root.strings[lang] ?? root.strings.en)[key] ?? root.strings.en[key];
        return (arg === undefined ? s : s.replace("%1", arg)).replace("%2", arg2 ?? "%2");
    }
    // A fact in the question's language.
    function factText(i, lang) {
        if (lang === "en" || !root.data.factsI18n?.[lang]) return root.data.facts[i];
        return root.data.factsI18n[lang][i] ?? root.data.facts[i];
    }

    // ------------------------------------------------------------ language
    // Lower case, no accents (đ→d, ß→ss), punctuation as spaces.
    function fold(text) {
        let s = (text ?? "").toLowerCase().replace(/đ/g, "d").replace(/ß/g, "ss");
        if (s.normalize) s = s.normalize("NFD").replace(/[̀-ͯ]/g, "");
        return s.replace(/[^a-z0-9+]+/g, " ").trim();
    }
    readonly property var langWords: ({
        en: ["help", "find", "tell", "know", "give", "the", "what", "whats", "how", "is", "do", "does", "my", "to", "for", "can", "which", "where", "show", "make", "take", "turn", "go", "next", "list", "every", "all", "shortcut", "hotkey", "window", "screen", "app", "lock", "close", "open", "change", "yo", "hey", "hi", "hello", "thanks", "please", "i", "you", "installed", "enabled", "this", "current", "sound", "up", "down", "history"],
        fr: ["comment", "quel", "que", "fait", "sert", "quelle", "quoi", "est", "raccourci", "raccourcis", "ouvrir", "fermer", "le", "la", "les", "des", "du", "pour", "une", "un", "je", "mon", "ma", "mes", "faire", "mettre", "aller", "suis", "puis", "fenetre", "ecran", "tous", "toutes", "liste", "active", "installe", "salut", "bonjour", "merci", "son", "presse", "plein", "monter", "baisser", "verrouiller", "changer"],
        de: ["wie", "was", "macht", "tut", "welche", "welches", "welcher", "ich", "das", "der", "die", "den", "dem", "ist", "offnen", "offne", "offnet", "fenster", "bildschirm", "mit", "und", "zum", "zur", "mein", "meine", "machen", "zeig", "alle", "aktiviert", "installiert", "hallo", "danke", "wechseln", "schliessen", "einstellungen", "tastenkurzel", "nachsten", "sperren", "andere", "vollbild", "aktiv"],
        vi: ["khong", "cua", "lam", "sao", "phim", "tat", "mo", "dong", "khoa", "man", "hinh", "nen", "cai", "dat", "so", "am", "luong", "chup", "the", "nao", "gi", "duoc", "bat", "co", "de", "la", "toi", "cach", "chuyen", "sang", "tang", "giam", "xin", "chao", "cam", "on", "ca", "liet", "ke", "doi", "nhanh", "toan", "bo", "nho", "tam", "lich", "su"]
    })
    function detectLang(text) {
        // Letters only Vietnamese uses (â/ê/ô are French too).
        if (/[ăđơưạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ]/i.test(text)) return "vi";
        const tokens = root.fold(text).split(" ");
        const score = { en: 0, fr: /[éèêàçùœâôî]/i.test(text) ? 2 : 0, de: /[äöüß]/i.test(text) ? 2 : 0, vi: 0 };
        for (const lang of ["en", "fr", "de", "vi"])
            for (const w of tokens) if (root.langWords[lang].includes(w)) score[lang] += 1;
        let best = "en";
        // Two hits, or one when nothing is English ("que fait Mod+R ?").
        for (const lang of ["fr", "de", "vi"])
            if (score[lang] >= (score.en === 0 ? 1 : 2) && score[lang] > score[best]) best = lang;
        // A single foreign word ("Vollbild", "Zwischenablage-Verlauf").
        if (best === "en" && score.en === 0) {
            for (const lang of ["de", "fr", "vi"])
                if (tokens.some(w => (root.lexicon[lang] ?? []).some(([p]) => !p.startsWith("=") && !p.includes(" ") && w.startsWith(p) && p.length >= 5)))
                    return lang;
        }
        return best;
    }

    // Lexicons onto the facts' English vocabulary. "=w" matches the word w
    // exactly; "a b" a phrase; anything else a word prefix (inflections).
    readonly property var lexicon: ({
        en: [["hotkey", "shortcut"], ["=float", "floating toggle"], ["=floating", "floating toggle"], ["=go", "focus"], ["=switch", "focus"], ["louder", "volume up raise"], ["quieter", "volume down lower"],
             ["=next", "below down"], ["previous", "above up"], ["=sound", "volume audio"], ["background", "wallpaper"],
             ["=panel", "sidebar"], ["=chat", "assistant ai"], ["=computer", "screen host"], ["=pc", "screen host"],
             ["=os", "nixos operating system"], ["what shell", "shell login"], ["which shell", "shell login"], ["my shell", "shell login"], ["distro", "nixos operating system"], ["hostname", "host name"],
             ["timezone", "time zone"], ["upgrad", "update"], ["=revert", "roll back undo"], ["rollback", "roll back undo"],
             ["=undo", "roll back undo"], ["cleanup", "free disk space garbage"], ["=clean", "free disk space garbage"],
             ["=storage", "disk space"], ["=wifi", "networkmanager network"], ["=internet", "network"],
             ["=language", "locale language"], ["=layout", "keyboard layout"], ["=logs", "logs journal"],
             ["=vm", "virtual machines"], ["=vms", "virtual machines"], ["=wm", "window manager desktop"],
             ["=dm", "login manager"], ["=specs", "system info"]],
        fr: [["ouvr", "open"], ["ferm", "close"], ["fenetre", "window"], ["raccourci", "shortcut"], ["touche", "key"],
             ["clavier", "keyboard"], ["lanceur", "launcher"], ["applic", "app"], ["=appli", "app"], ["logiciel", "app package"],
             ["fond d ecran", "wallpaper"], ["=fond", "wallpaper"], ["capture d ecran", "screenshot"], ["capture", "screenshot"],
             ["plein ecran", "fullscreen"], ["ecran", "screen"], ["flott", "floating toggle"], ["=aller", "focus"], ["=passer", "focus"], ["mosaique", "tiled"],
             ["parametres rapides", "quick settings sidebar right"], ["parametre rapide", "quick settings sidebar right"], ["reglages rapides", "quick settings sidebar right"],
             ["parametre", "setting"], ["reglage", "setting"], ["rapide", "quick"], ["verrou", "lock"], ["deconne", "logout"],
             ["eteind", "shutdown power"], ["redemarr", "reboot"], ["veille", "suspend sleep"], ["=son", "volume audio"],
             ["volume", "volume"], ["monte", "up raise"], ["augment", "up raise"], ["baiss", "down lower"], ["diminu", "down lower"],
             ["luminos", "brightness"], ["terminal", "terminal"], ["console", "terminal"], ["espace de travail", "workspace"],
             ["=bureau", "workspace"], ["suivant", "next below"], ["precedent", "previous above"], ["presse papier", "clipboard"],
             ["historique", "history"], ["barre", "bar"], ["cach", "hide"], ["masqu", "hide"], ["affich", "show"],
             ["panneau", "sidebar"], ["gauche", "left"], ["droite", "right"], ["=haut", "above up"], ["=bas", "below down"],
             ["colonne", "column"], ["deplac", "move"], ["activ", "enabled"], ["install", "installed"], ["paquet", "package"],
             ["=tous", "all"], ["=toutes", "all"], ["liste", "list"], ["=chat", "chat assistant"], ["=ia", "ai"],
             ["assistant", "assistant"], ["traduc", "translator"], ["notif", "notification"], ["calendrier", "calendar"],
             ["configur", "configure setting"], ["appliqu", "apply"], ["modif", "change"], ["chang", "change"],
             ["alimentation", "power"], ["maximis", "maximize"], ["centr", "center"], ["cafe", "caffeine idle"],
             ["enregistr", "record"], ["copi", "copy"], ["texte", "text"],
             ["noyau", "kernel"], ["nom d hote", "host name"], ["=hote", "host"], ["fuseau", "time zone"], ["langue", "language locale"],
             ["disposition", "layout"], ["demarrage", "boot"], ["chargeur", "bootloader"], ["mise a jour", "update"],
             ["mettre a jour", "update"], ["revenir", "roll back undo"], ["annul", "undo roll back"], ["arriere", "back"],
             ["espace disque", "free disk space"], ["nettoy", "free disk space garbage"], ["liber", "free"], ["cherch", "find search"],
             ["trouv", "find"], ["essay", "try"], ["journaux", "logs"], ["utilisateur", "user"], ["compte", "account user"],
             ["editeur", "editor"], ["systeme d exploitation", "operating system nixos"], ["pare feu", "firewall"],
             ["impression", "printing"], ["imprim", "printing"], ["reseau", "network"], ["machines virtuelles", "virtual machines"],
             ["conteneur", "containers"], ["ecran de connexion", "login screen"], ["gestionnaire de connexion", "login manager"],
             ["empreinte", "fingerprint"], ["batterie", "battery"], ["infos systeme", "system info"], ["information", "info"]],
        de: [["offn", "open"], ["schliess", "close"], ["fenster", "window"], ["tastenkurz", "shortcut"], ["kurzel", "shortcut"],
             ["tastatur", "keyboard"], ["=taste", "key"], ["starter", "launcher"], ["programm", "app"], ["=app", "app"],
             ["anwendung", "app"], ["hintergrund", "wallpaper"], ["bildschirmfoto", "screenshot"], ["screenshot", "screenshot"],
             ["bildschirm", "screen"], ["schweb", "floating toggle"], ["kachel", "tiled"], ["einstellung", "setting"],
             ["schnelleinstellung", "quick settings sidebar right"], ["schnell", "quick"], ["sperr", "lock"], ["abmeld", "logout"], ["herunterfahr", "shutdown power"],
             ["ausschalt", "off power"], ["neustart", "reboot"], ["neu starten", "reboot"], ["ruhezustand", "suspend"],
             ["standby", "suspend"], ["=ton", "volume audio"], ["lautstark", "volume"], ["lauter", "up raise volume"],
             ["leiser", "down lower volume"], ["erhoh", "up raise"], ["verringer", "down lower"], ["helligkeit", "brightness"],
             ["terminal", "terminal"], ["konsole", "terminal"], ["arbeitsbereich", "workspace"], ["arbeitsflache", "workspace"],
             ["nachst", "next below"], ["vorherig", "previous above"], ["vollbild", "fullscreen"], ["zwischenablage", "clipboard"],
             ["verlauf", "history"], ["seitenleiste", "sidebar"], ["leiste", "bar"], ["ausblend", "hide"], ["versteck", "hide"],
             ["einblend", "show"], ["zeig", "show"], ["=links", "left"], ["=rechts", "right"], ["=oben", "above up"],
             ["=unten", "below down"], ["spalte", "column"], ["verschieb", "move"], ["aktiv", "enabled"], ["installiert", "installed"],
             ["paket", "package"], ["=alle", "all"], ["liste", "list"], ["=ki", "ai"], ["=chat", "chat assistant"],
             ["ubersetz", "translator"], ["benachrichtigung", "notification"], ["kalender", "calendar"], ["wechsel", "focus"],
             ["konfigur", "configure setting"], ["anwend", "apply"], ["ander", "change"], ["energie", "power"],
             ["maximier", "maximize"], ["zentrier", "center"], ["koffein", "caffeine idle"], ["aufnehm", "record"], ["kopier", "copy"],
             ["rechnername", "host name computer"], ["zeitzone", "time zone"], ["sprache", "language locale"],
             ["tastaturlayout", "keyboard layout"], ["aktualisier", "update"], ["zurucksetz", "roll back undo"], ["zuruck", "back roll"],
             ["ruckgangig", "undo roll back"], ["speicherplatz", "free disk space"], ["aufraum", "free disk space garbage"],
             ["=such", "find search"], ["=suche", "find search"], ["finde", "find"], ["ausprobier", "try"], ["protokoll", "logs"],
             ["benutzer", "user"], ["=konto", "account user"], ["=konten", "account user"], ["betriebssystem", "operating system nixos"],
             ["=drucken", "printing"], ["=drucker", "printing"], ["netzwerk", "network"], ["virtuelle maschine", "virtual machines"],
             ["anmeldebildschirm", "login screen"], ["anmeldemanager", "login manager"], ["fingerabdruck", "fingerprint"],
             ["=akku", "battery"], ["=dienst", "service"], ["systeminfo", "system info"], ["freigeb", "free"]],
        vi: [["phim tat", "shortcut"], ["=phim", "key"], ["=mo", "open"], ["=dong", "close"], ["cua so", "window"],
             ["trinh khoi chay", "launcher"], ["khoi chay", "launcher"], ["ung dung", "app"], ["hinh nen", "wallpaper"],
             ["chup man hinh", "screenshot"], ["=chup", "screenshot"], ["toan man hinh", "fullscreen"], ["man hinh", "screen"],
             ["=noi", "floating toggle"], ["chuyen sang", "focus"], ["chuyen den", "focus"], ["xep o", "tiled"], ["cai dat nhanh", "quick settings sidebar right"], ["cai dat", "setting"], ["=nhanh", "quick"], ["=khoa", "lock"],
             ["dang xuat", "logout"], ["tat may", "shutdown power"], ["khoi dong lai", "reboot"], ["=ngu", "suspend sleep"],
             ["am luong", "volume"], ["=tang", "up raise"], ["=giam", "down lower"], ["do sang", "brightness"],
             ["=terminal", "terminal"], ["khong gian lam viec", "workspace"], ["tiep theo", "next below"], ["ke tiep", "next below"],
             ["=truoc", "previous above"], ["bo nho tam", "clipboard"], ["=clipboard", "clipboard"], ["lich su", "history"],
             ["=thanh", "bar"], ["=an", "hide"], ["=hien", "show"], ["=bang", "sidebar"], ["=trai", "left"], ["=phai", "right"],
             ["=tren", "above up"], ["=duoi", "below down"], ["=cot", "column"], ["di chuyen", "move"], ["=chuyen", "focus"],
             ["=bat", "enabled"], ["kich hoat", "enabled"], ["da cai", "installed"], ["duoc cai", "installed"], ["cai chua", "installed"],
             ["=goi", "package"], ["phan mem", "app package"], ["tat ca", "all"], ["liet ke", "list"], ["danh sach", "list"],
             ["tro ly", "assistant"], ["=chat", "chat assistant"], ["=ai", "ai"], ["=dich", "translator"], ["thong bao", "notification"],
             ["=lich", "calendar"], ["ap dung", "apply"], ["thay doi", "change"], ["=doi", "change"], ["=nguon", "power"],
             ["phong to", "maximize"], ["can giua", "center"], ["tat tieng", "mute"], ["tat am", "mute"],
             ["tat man hinh", "monitors off"], ["=tieng", "volume audio"], ["=tat", "off"],
             ["he dieu hanh", "operating system nixos"], ["=nhan", "kernel"], ["phien ban", "version"], ["ten may", "host name"],
             ["mui gio", "time zone"], ["ngon ngu", "language locale"], ["bo cuc", "layout"], ["ban phim", "keyboard"],
             ["khoi dong", "boot"], ["cap nhat", "update"], ["quay lai", "roll back"], ["hoan tac", "undo"], ["the he", "generation"],
             ["dung luong", "disk space"], ["giai phong", "free"], ["don rac", "garbage"], ["=tim", "find search"], ["dung thu", "try"],
             ["nhat ky", "logs"], ["nguoi dung", "user"], ["tai khoan", "account"], ["soan thao", "editor"], ["tuong lua", "firewall"],
             ["=mang", "network"], ["may ao", "virtual machines"], ["dang nhap", "login"], ["van tay", "fingerprint"],
             ["dich vu", "service"], ["thong tin he thong", "system info"], ["thong tin", "info"]]
    })
    // English words for the question: its words mapped through the
    // lexicons (the detected language's, plus French/German — cognates are
    // rare — and the English extras; Vietnamese only when detected, its
    // one-syllable words are too ambiguous). Phrases first, then per word the
    // longest match; a matched word is replaced by its translation
    // ("fond d'écran" → wallpaper, not also "écran" → screen).
    function translate(question, lang) {
        let folded = ` ${root.fold(question)} `;
        const langs = [lang, "fr", "de", "en"].filter((l, i, a) => a.indexOf(l) === i && (l !== "vi" || lang === "vi"));
        // English extras add words, they don't replace them.
        const entries = [].concat(...langs.map(l => (root.lexicon[l] ?? []).map(([p, e]) => [p, e, l === "en"])));
        const extra = [];
        const consumed = [];
        for (const [pattern, english] of entries.filter(([p]) => p.includes(" ")).sort((a, b) => b[0].length - a[0].length)) {
            if (folded.includes(` ${pattern} `)) {
                extra.push(english);
                consumed.push(...pattern.split(" "));
                folded = folded.split(` ${pattern} `).join(" ");
            }
        }
        const kept = [];
        for (const w of folded.trim().split(/\s+/).filter(x => x.length > 0)) {
            let best = null;
            for (const [pattern, english, additive] of entries) {
                if (pattern.includes(" ")) continue;
                const exact = pattern.startsWith("=");
                const p = exact ? pattern.slice(1) : pattern;
                if (exact ? w === p : w.startsWith(p))
                    if (!best || p.length > best.p.length) best = { p, english, additive };
            }
            if (best) extra.push(best.english);
            if (best && !best.additive) consumed.push(w);
            else kept.push(w);
        }
        let text = `${kept.join(" ")} ${extra.join(" ")}`;
        // Closing an "app" / "program" closes its window.
        if (/\bclose\b/.test(text)) text = text.replace(/\b(apps?|application|program)\b/g, "window");
        return { text, consumed: new Set(consumed) };
    }
    function englishText(question, lang) {
        return root.translate(question, lang).text;
    }

    // ------------------------------------------------------------ retrieval
    // What retrieval matches a fact on: the distinctive part only.
    function indexText(fact, kind) {
        // A discovered toggle: its option path only (the description is for
        // reading; its words would match unrelated questions).
        if (kind?.startsWith("toggle:"))
            return `${kind.slice(7).replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[._-]/g, " ")} enabled`;
        let m = fact.match(/^The shell setting (\S+) is set in Nix to (.*)\.$/);
        if (m) return `setting ${m[1].replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[._]/g, " ")} ${m[2]}`;
        m = fact.match(/^The package (\S+) is installed\.$/);
        if (m) return m[1].replace(/[-_.]/g, " ");
        return fact;
    }

    function load(text) {
        try {
            const d = JSON.parse(text);
            const fw = d.facts.map((f, i) => new Set(root.words(root.indexText(f, d.kinds?.[i]))));
            const df = {};
            for (const set of fw)
                for (const w of set)
                    df[w] = (df[w] ?? 0) + 1;
            const idf = {};
            for (const w in df)
                idf[w] = Math.log(d.facts.length / df[w]);
            root._factWords = fw;
            root._idf = idf;
            root._maxIdf = Math.log(d.facts.length);
            root._settingPaths = new Set(d.settingPaths ?? []);
            root.data = d;
        } catch (e) {
            console.warn("[ConfigAssistant] invalid system-facts.json:", e);
            root.data = null;
        }
    }

    readonly property var stopWords: new Set(("a an the is are am to of in on for with my me i do does how what which where when can could "
        + "should would it this that and or by from be use using key keyboard shortcut shortcuts bind binding press open get "
        + "spawn launch bring mean meant want need please there way make you your yo whats current this put set run running").split(" "))
    readonly property var synonyms: ({
        "launcher": ["search", "app"], "app": ["launcher"], "screenshot": ["screen"], "float": ["floating"],
        "floating": ["tiled"], "terminal": ["kitty"], "lock": ["session"], "logout": ["log", "session"],
        "shutdown": ["shut", "power"], "poweroff": ["power"], "volume": ["audio"], "sound": ["audio", "volume"],
        "notification": ["notification"], "setting": ["configure"], "configure": ["setting"], "config": ["setting", "configure"],
        "configuration": ["setting", "configure"], "preference": ["setting"], "option": ["setting"],
        "disappear": ["hide"], "caffeine": ["idle"], "awake": ["idle", "display"], "sleep": ["suspend", "idle"],
        "screen": ["display"], "display": ["screen"], "copy": ["clipboard"], "paste": ["clipboard"],
        "capture": ["screenshot"], "snip": ["screenshot"], "log": ["session"], "restart": ["reboot"],
        "background": ["wallpaper"], "panel": ["sidebar"], "chat": ["assistant", "ai"], "raise": ["up"],
        "lower": ["down"], "next": ["below"], "previous": ["above"], "history": ["clipboard"],
        "vim": ["neovim"], "nvim": ["neovim"], "nixvim": ["neovim"]
    })

    function stem(w) {
        // Plural first, so "settings" and "setting" meet ("sett").
        if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss") && !/(s|x|z|ch|sh)es$/.test(w)) w = w.slice(0, -1);
        if (w.length > 5 && w.endsWith("ing")) return w.slice(0, -3);
        if (w.length > 4 && w.endsWith("ed")) return w.slice(0, -2);
        if (w.length > 4 && /(s|x|z|ch|sh)es$/.test(w)) return w.slice(0, -2);
        if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss")) return w.slice(0, -1);
        return w;
    }
    function words(text) {
        // Single letters are noise ("what's" → "s", which matched Mod+S).
        return (text.toLowerCase().match(/[a-z0-9]+/g) ?? []).filter(w => w.length > 1 && !root.stopWords.has(w))
            .map(w => root.stem(w)).filter(w => !root.stopWords.has(w));
    }

    // { facts: [{score, fact, i}] best first, coverage: 0..1 } — coverage is
    // how much of the question (IDF-weighted; words no fact contains weigh
    // the most) its best fact explains. For other languages only the English
    // words (own + lexicon) count: untranslated function words would drown it.
    function lookup(question, previous = "", lang = "en") {
        if (!root.data) return { facts: [], coverage: 0 };
        const direct = new Set(root.words(root.englishText(question, lang)));
        const context = new Set(root.words(root.englishText(previous, lang)).filter(w => !direct.has(w)));
        const extra = new Set();
        for (const w of direct)
            for (const s of (root.synonyms[w] ?? []))
                if (!direct.has(s)) extra.add(s);
        const weight = w => root._idf[w] ?? 0;
        // Neovim keymaps for questions about vim, the rest for the others.
        const vim = root.aboutVim(question);
        const scored = [];
        root.data.facts.forEach((fact, i) => {
            const fw = root._factWords[i];
            let score = 0;
            for (const w of direct) if (fw.has(w)) score += weight(w);
            for (const w of extra) if (fw.has(w)) score += 0.5 * weight(w);
            for (const w of context) if (fw.has(w)) score += 0.5 * weight(w);
            if (root.isNvim(i) !== vim) score *= 0.5;
            // Statements about the system before the many discovered toggles.
            if (root.data.kinds?.[i]?.startsWith("toggle:")) score *= 0.7;
            if (score > 0) scored.push({ score, fact, i });
        });
        // Ties (e.g. "settings": every pinned shell setting matches too): the
        // keybindings first — what can be done beats what is configured.
        scored.sort((a, b) => (b.score - a.score) || (root.isBind(b.i) - root.isBind(a.i)));
        if (scored.length === 0 || direct.size === 0) return { facts: scored.slice(0, 6), coverage: 0 };
        const top = scored[0].score;
        const facts = scored.filter(s => s.score >= 0.5 * top).slice(0, 6);
        let total = 0, covered = 0;
        const unknown = []; // content words no fact contains ("record" in "record my screen")
        const best = root._factWords[scored[0].i];
        for (const w of direct) {
            if (lang !== "en" && root._idf[w] === undefined) continue; // untranslated foreign word
            if (lang === "en" && root._idf[w] === undefined && root.langWords.en.includes(w)) continue; // filler
            if (root._idf[w] === undefined && w.length >= 4) unknown.push(w);
            const wt = root._idf[w] ?? root._maxIdf;
            total += wt;
            if (best.has(w)) covered += wt;
            else if ((root.synonyms[w] ?? []).some(s => best.has(s))) covered += wt / 2;
        }
        return { facts, coverage: total > 0 ? covered / total : 0, unknown };
    }


    // ------------------------------------------------------------ intents
    readonly property var keybindAsk: /shortcut|keybind|keymap|mapping|hotkey|keyboard|\bkeys?\b|\bpress|\bbind|raccourci|touche|clavier|tastenk|kurzel|\btaste|tastatur|belegung|phim tat|\bphim\b/
    // About Neovim ("vim shortcut to find files", "what does <leader>ff do").
    readonly property var vimAsk: /\b(n?vim|neovim|nixvim)\b|<leader>|<localleader>/i
    readonly property var howAsk: /^\s*(how|what should|can i|is there a way|comment|wie|lam sao|lam the nao|cach)\b/
    readonly property var whyAsk: /^\s*(why|what could|what can cause|pourquoi|warum|wieso|tai sao|vi sao)\b|\bcause\b/
    readonly property var enableAsk: /enabled|\benable|\bactive|\bturned on|\bon this machine|\busing\b|\bon\b|\bhave\b|\bactiv|\baktiv|\bbat\b|kich hoat|\bdung\b/
    readonly property var installAsk: /\binstall|\bhave\b|\bknow\b|\bavailable\b|\bconnai|\bkenn|\bbiet\b|\bcai\b|\bco\b.*\bkhong\b/
    function mentions(foldedQuestion, name) {
        return new RegExp(`\\b${root.escapeRe(root.fold(name))}\\b`).test(foldedQuestion);
    }
    function isNvim(i) {
        return root.data.kinds?.[i]?.startsWith("nvim:") ?? false;
    }
    function aboutVim(question) {
        return root.vimAsk.test(question) || root.vimAsk.test(root.fold(question));
    }
    // A Neovim keymap as a list line: "- **<leader>ff** (normal mode): run :Telescope find_files"
    function formatNvim(i, lang) {
        const km = root.data.nvim.keymaps[Number(root.data.kinds[i].slice(5))];
        return `- **${km.key}** (${km.where[lang] ?? km.where.en}): ${km.desc[lang] ?? km.desc.en}`;
    }
    // Canonical Neovim key: <…> parts are case-insensitive with sorted
    // modifiers (<S-C-u> = <c-s-U>), the rest is case-sensitive (gd ≠ gD).
    function nvimKey(k) {
        const leader = root.data?.nvim?.leader === "Space" ? "<leader>" : "<space>";
        return k.replace(/<([^<>]+)>/g, (_, inner) => {
            const parts = inner.toLowerCase().split("-");
            const key = parts.length > 1 && parts[parts.length - 1] === "" ? "-" : parts.pop();
            const name = `<${parts.filter(p => p !== "").sort().concat([key]).join("-")}>`;
            return name === "<space>" ? leader : name;
        });
    }
    // The Neovim keys a question names: <…> notation, "ctrl+p" when about
    // vim, and plain configured keys ("gd") when about vim.
    function nvimKeysIn(question) {
        const keys = root.allMatches(/(?:<[A-Za-z][\w-]*>)+[^\s?!,;"'`“”]*/g, question).map(m => m[0].replace(/[.:]$/, ""));
        if (root.aboutVim(question)) {
            const mods = { ctrl: "C", control: "C", shift: "S", alt: "M", meta: "M" };
            for (const m of root.allMatches(/((?:(?:ctrl|control|shift|alt|meta)\s*\+\s*)+)([a-z0-9]+)/gi, question))
                keys.push(`<${m[1].split("+").map(x => mods[x.trim().toLowerCase()]).filter(x => x).join("-")}-${m[2]}>`);
            const known = new Set(root.data.nvim.keymaps.map(km => km.key));
            for (const w of question.split(/[\s?!,;"'`“”]+/))
                if (known.has(w) && !keys.includes(w)) keys.push(w);
        }
        return keys;
    }
    function isBind(i) {
        return root.data.kinds ? root.data.kinds[i].startsWith("bind:") : root.data.facts[i].startsWith("Press ");
    }
    function bindKey(i) {
        if (root.data.kinds?.[i]?.startsWith("bind:")) return root.normKey(root.data.kinds[i].slice(5));
        return root.normKey(root.data.facts[i].split(" ")[1]);
    }
    // A binding as a list line, in the question's language: "- **Mod+D**: open …"
    function formatBind(i, lang) {
        const key = root.data.kinds?.[i]?.startsWith("bind:") ? root.data.kinds[i].slice(5) : root.data.facts[i].split(" ")[1];
        const text = root.factText(i, lang)
            .replace(/^(Press|Appuyez sur|Nhấn) \S+ (to|pour|để) /, "")
            .replace(new RegExp(`^${root.escapeRe(key)} – `), "")
            .replace(/\.$/, "");
        return `- **${key}**: ${text}`;
    }

    // ------------------------------------------------------------ listings
    function listReply(question, lang) {
        const q = root.fold(question);
        const listing = /\b(all|list|every|cheat ?sheet|overview|tous|toutes|liste|alle|zeig|tat ca|liet ke|danh sach|toan bo)\b/.test(q)
            || /\b(keybinds|keymaps|mappings|shortcuts|bindings|hotkeys|modules|packages|services|programs|raccourcis|paquets|pakete|dienste|programme)\b/.test(q);
        if (!listing) return null;
        const facts = root.data.facts;
        if (root.aboutVim(question)) {
            const keymaps = facts.map((_, i) => i).filter(i => root.isNvim(i));
            if (keymaps.length === 0) return root.tr(lang, "nvimNone");
            const generic = new Set(["all", "list", "every", "each", "show", "available", "overview", "cheat", "sheet",
                "keybind", "keymap", "mapping", "hotkey", "shortcut", "binding", "key", "the", "me", "here", "have", "exist",
                "current", "configured", "vim", "nvim", "neovim", "nixvim", "in"]);
            const topic = new Set(root.words(root.englishText(question, lang)).filter(w => !generic.has(w) && (root._idf[w] ?? 0) > 0));
            for (const w of [...topic])
                for (const s of (root.synonyms[w] ?? [])) topic.add(s);
            let selected = keymaps;
            if (topic.size > 0) {
                const matching = keymaps.filter(i => [...topic].some(w => root._factWords[i].has(w)));
                if (matching.length > 0) selected = matching;
            }
            const leader = root.data.nvim.leader;
            const title = selected === keymaps ? root.tr(lang, "nvimShortcuts", keymaps.length, leader) : root.tr(lang, "nvimMatching", leader);
            return `${title}\n${selected.map(i => root.formatNvim(i, lang)).join("\n")}`;
        }
        if (root.keybindAsk.test(q)) {
            const binds = facts.map((_, i) => i).filter(i => root.isBind(i));
            const generic = new Set(["all", "list", "every", "each", "show", "available", "overview", "cheat", "sheet",
                "keybind", "hotkey", "shortcut", "binding", "key", "the", "me", "here", "have", "exist", "current", "configured"]);
            // Topic words: the English (and lexicon) words that aren't about listing.
            const topic = new Set(root.words(root.englishText(question, lang)).filter(w => !generic.has(w) && (root._idf[w] ?? 0) > 0));
            for (const w of [...topic])
                for (const s of (root.synonyms[w] ?? [])) topic.add(s);
            let selected = binds;
            if (topic.size > 0) {
                const matching = binds.filter(i => [...topic].some(w => root._factWords[i].has(w)));
                if (matching.length > 0) selected = matching;
            }
            const title = selected === binds ? root.tr(lang, "allShortcuts", binds.length) : root.tr(lang, "matching");
            return `${title}\n${selected.map(i => root.formatBind(i, lang)).join("\n")}`;
        }
        if (/\b(services?|programs?|dienste?|programme|dich vu|chuong trinh|option)\b/.test(q) && (root.data.toggles ?? []).length > 0) {
            const on = root.data.toggles.filter(tg => tg.enabled);
            const group = scope => on.filter(tg => tg.scope === scope).map(tg => tg.path).join(", ");
            return root.tr(lang, "enabledToggles", root.data.host ?? "")
                + `\n- NixOS: ${group("nixos") || "–"}\n- Home Manager: ${group("home-manager") || "–"}`;
        }
        if (/\bmodul/.test(q)) {
            const off = root.data.modules.all.filter(m => !root.data.modules.enabled.includes(m));
            return root.tr(lang, "enabledModules", root.data.host ?? "") + `\n${root.data.modules.enabled.join(", ")}\n\n`
                + root.tr(lang, "notEnabled") + `\n${off.join(", ")}`;
        }
        if (/\b(settings?|reglages?|einstellungen|thiet lap)\b/.test(q) && /\bnix\b|pinned|locked|verrouill|gesperrt/.test(q)) {
            const pinned = facts.filter(f => f.startsWith("The shell setting "))
                .map(f => f.replace(/^The shell setting (\S+) is set in Nix to (.*)\.$/, "- `$1` = `$2`"));
            return root.tr(lang, "pinned") + `\n${pinned.join("\n")}`;
        }
        if (/\b(packages?|paquets?|pakete?|goi|installed|installes?|installiert|da cai)\b/.test(q))
            return root.tr(lang, "packages", root.data.packages.length) + `\n${root.data.packages.join(", ")}`;
        return null;
    }

    // "system info", "about this machine", "neofetch": every system fact.
    function systemInfoReply(question, lang) {
        const en = ` ${root.englishText(question, lang)} ${root.fold(question)} `;
        const asked = /\b(neofetch|fastfetch|specs)\b/.test(en)
            || (/\b(system|os|machine|computer|nixos)\b/.test(en) && /\b(info|infos|information|summary|overview|details|about)\b/.test(en));
        if (!asked) return null;
        const facts = root.data.facts.map((_, i) => i).filter(i => root.data.kinds?.[i] === "os");
        if (facts.length === 0) return null;
        return root.tr(lang, "sysInfo", root.data.host ?? "") + "\n" + facts.map(i => `- ${root.factText(i, lang)}`).join("\n");
    }
    // A statement about the system (os), a how-to or a core fact.
    function isInfo(i) {
        const k = root.data.kinds?.[i] ?? "";
        return k === "os" || k === "core" || k.startsWith("howto:") || k.startsWith("toggle:");
    }
    // "Is bluetooth enabled?", "do I have docker?": the discovered option sets
    // (<path>.enable) the question names, by their last component ("ssh" finds
    // services.openssh). Exact names win over partial ones; null when none.
    function toggleReply(question, lang) {
        const toggles = root.data.toggles ?? [];
        if (toggles.length === 0) return null;
        const fold = w => w.toLowerCase().replace(/[^a-z0-9]/g, "");
        const english = root.englishText(question, lang);
        const generic = ["enabled", "enable", "install", "installed", "running", "active", "service", "services", "program",
            "programs", "system", "machine", "server", "client", "daemon", "support", "have", "there", "any", "use", "using"];
        // Other languages: only the translated words (untranslated function
        // words such as "est" would match option names).
        const function_ = new Set([].concat(...Object.values(root.langWords)));
        const words = [...new Set(`${lang === "en" ? root.fold(question) : ""} ${english}`.split(/\s+/).map(fold))]
            .filter(w => w.length >= 3 && !root.stopWords.has(w) && !function_.has(w) && !generic.includes(w));
        const name = tg => fold(tg.path.split(".").pop());
        // The name itself or one ending in it ("ssh": programs.ssh,
        // services.openssh); else one starting with or containing it.
        let hits = toggles.filter(tg => words.some(w => name(tg) === w || name(tg).endsWith(w)));
        if (hits.length === 0)
            hits = toggles.filter(tg => words.some(w => w.length >= 4 && name(tg).includes(w)));
        if (hits.length === 0 || hits.length > 8) return null;
        const label = tg => `${tg.path} (${tg.scope === "home-manager" ? "Home Manager" : "NixOS"})`;
        // The name itself first; a long list of what is off is cut short.
        hits.sort((a, b) => words.includes(name(b)) - words.includes(name(a)));
        const on = hits.filter(tg => tg.enabled), off = hits.filter(tg => !tg.enabled).slice(0, 4);
        const lines = [];
        if (on.length > 0) lines.push(root.tr(lang, "toggleYes", on.map(label).join(", ")));
        if (off.length > 0) lines.push(root.tr(lang, "toggleNo", off.map(label).join(", ")));
        return lines.join("\n");
    }

    // ------------------------------------------------------------ direct answers
    // A direct answer from the configuration, or null (answer() then lists the closest facts).
    // The chat's reply when the config assistant is selected (no model is
    // ever called): a direct answer, else the closest facts, else "I don't
    // know" with tips on how to ask.
    function answer(question, previous = "") {
        return root.codeKeys(root.answerText(question, previous));
    }
    // Vim key notation (<leader>ff, <C-p>) as code spans: the chat renders
    // Markdown, which takes <…> for an HTML tag and drops it. Existing code
    // spans are left alone; trailing punctuation stays outside.
    function codeKeys(text) {
        return text.replace(/(`[^`]*`)|([^\s`*“”"(]*<[A-Za-z][\w-]*>[^\s`*“”"]*?)(?=[.,:;!?)”"*]*(?:\s|$))/g,
            (m, code, key) => code ?? `\`${key}\``);
    }
    function answerText(question, previous) {
        const quick = root.quickReply(question, previous);
        if (quick !== null) return quick;
        const lang = root.detectLang(question);
        const found = root.lookup(question, previous, lang);
        // Keybindings first: what can be done beats what is configured.
        const isKey = i => root.isBind(i) || root.isNvim(i);
        const close = found.facts.filter(f => isKey(f.i))
            .concat(found.facts.filter(f => !isKey(f.i))).slice(0, 3);
        if (close.length === 0 || found.coverage < 0.25)
            return `${root.tr(lang, "dontKnow")}\n\n${root.tr(lang, "tips")}`;
        return `${root.tr(lang, "notSure")}\n${close.map(f => `- ${root.factText(f.i, lang)}`).join("\n")}`;
    }

    function quickReply(question, previous = "") {
        if (!root.data) return null;
        const lang = root.detectLang(question);
        const q = root.fold(question);
        if (/^(hi|hello|hey|yo|hiya|good (morning|afternoon|evening)|bonjour|salut|coucou|hallo|guten (tag|morgen|abend)|moin|servus|xin chao|chao)\b[\s!.,?]*$/.test(q))
            return `${root.tr(lang, "hi")} ${root.tr(lang, "capabilities")}\n\n${root.tr(lang, "tips")}`;
        if (/^(thanks|thank you|thx|merci|danke|cam on|ok|okay|cool|great|nice|super|parfait|gut|tot)\b[\s!.,]*$/.test(q))
            return root.tr(lang, "welcome");
        const helpWord = /^(help|aide|hilfe|tro giup|giup|giup do|\?)[\s!.?]*$/.exec(q);
        if (helpWord)
            return root.helpText(({ aide: "fr", hilfe: "de", giup: "vi", "giup do": "vi", "tro giup": "vi" })[helpWord[1]] ?? lang);
        const listing = root.listReply(question, lang);
        if (listing !== null) return listing;
        const info = root.systemInfoReply(question, lang);
        if (info !== null) return info;

        // "Is <module> enabled?" — from the module lists.
        const mod = root.data.modules.all.find(m => root.mentions(q, m));
        if (mod && root.enableAsk.test(q) && !root.keybindAsk.test(q))
            return root.data.modules.enabled.includes(mod) ? root.tr(lang, "modYes", mod) : root.tr(lang, "modNo", mod);
        // "Is bluetooth enabled?", "do I have docker?" — the discovered option
        // sets ("is firefox installed?" stays a package question).
        if (root.enableAsk.test(q) && !root.keybindAsk.test(q) && !root.aboutVim(question) && !/\binstall|\bcai\b/.test(q)) {
            const toggle = root.toggleReply(question, lang);
            if (toggle !== null) return toggle;
        }
        // "Is <package> installed?" / "do you know <package>?"
        const pkg = root.data.packages.find(p => p.length > 2 && root.mentions(q, p));
        if (pkg && root.installAsk.test(q) && !root.keybindAsk.test(q))
            return /\binstall|\bcai\b/.test(q) ? root.tr(lang, "pkgYes", pkg) : root.tr(lang, "pkgKnown", pkg);
        // "Is firefox installed?" when it comes from programs.firefox.enable.
        if (!pkg && root.installAsk.test(q) && !root.keybindAsk.test(q) && !root.aboutVim(question)) {
            const toggle = root.toggleReply(question, lang);
            if (toggle !== null) return toggle;
        }

        // "What does <leader>ff do (in vim)?" — the Neovim keymap(s) of that key.
        const vimKeys = root.data.nvim ? root.nvimKeysIn(question) : [];
        if (vimKeys.length > 0) {
            const lines = [];
            for (const k of vimKeys) {
                const found = root.data.facts.map((_, j) => j).filter(j => root.isNvim(j)
                    && root.nvimKey(root.data.nvim.keymaps[Number(root.data.kinds[j].slice(5))].key) === root.nvimKey(k));
                if (found.length === 0) lines.push(root.tr(lang, "nvimUnbound", k));
                for (const j of found) lines.push(root.factText(j, lang));
            }
            return lines.filter((l, j) => lines.indexOf(l) === j).join("\n");
        }
        // "What does Mod+R do?" — the key's own binding.
        const keys = root.allMatches(/(?:(?:mod|super|ctrl|control|alt|shift|win(?:dows)?)\s*\+\s*)+[a-z0-9_]+/gi, question)
            .concat(root.allMatches(/\bPrint\b|XF86\w+/g, question)).map(m => m[0]);
        if (keys.length > 0) {
            const lines = keys.map(k => {
                const i = root.data.facts.findIndex((_, j) => root.isBind(j) && root.bindKey(j) === root.normKey(k));
                return i >= 0 ? root.factText(i, lang) : root.tr(lang, "unbound", k.replace(/\s+/g, ""));
            });
            return lines.filter((l, j) => lines.indexOf(l) === j).join("\n");
        }

        const found = root.lookup(question, previous, lang);
        // A request a keybinding clearly answers: the binding (key + what it
        // does), plus a close second one. Not for "why …" questions.
        // The best binding, if close to the best fact overall (a wallpaper
        // *setting* shouldn't hide the wallpaper selector's key).
        const isKey = root.aboutVim(question) ? root.isNvim : root.isBind;
        const top = found.facts.find(s => isKey(s.i) && s.score >= 0.75 * found.facts[0].score);
        // Not when the question names something no fact mentions: "record my
        // screen" isn't answered by the screenshot key (answer() then lists
        // the closest facts instead).
        if (top && found.coverage >= 0.35 && (found.unknown ?? []).length === 0 && !root.whyAsk.test(q)) {
            const second = found.facts.find(s => s !== top && isKey(s.i) && s.score >= 0.85 * top.score
                && root.factText(s.i, "en") !== root.factText(top.i, "en") && (isKey !== root.isBind || root.bindKey(s.i) !== root.bindKey(top.i)));
            return root.factText(top.i, lang) + (second ? `\n${root.tr(lang, "also")} ${root.factText(second.i, lang)}` : "");
        }
        // A question about the system or how to do something: the best
        // statement, plus a close second one.
        const best = found.facts[0];
        if (best && root.isInfo(best.i) && (found.coverage >= 0.5
                || (found.coverage >= 0.35 && (found.unknown ?? []).length === 0))) {
            const second = found.facts.find(s => s !== best && root.isInfo(s.i) && s.score >= 0.85 * best.score);
            return root.factText(best.i, lang) + (second ? `\n${root.tr(lang, "also")} ${root.factText(second.i, lang)}` : "");
        }
        if (found.facts.length === 0 || found.coverage < 0.25)
            return `${root.tr(lang, "dontKnow")}\n\n${root.tr(lang, "tips")}`;
        return null;
    }

    // Canonical key combo: "super + shift+e" = "Shift+Mod+E" = "mod+shift+e".
    function normKey(k) {
        const parts = k.replace(/\s+/g, "").replace(/super|windows|win/gi, "Mod").replace(/control/gi, "Ctrl")
            .toLowerCase().split("+");
        const key = parts.pop();
        return parts.sort().concat([key]).join("+");
    }
    function escapeRe(s) {
        return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }
    // All matches of a global regex (QML's JS engine has no String.matchAll).
    function allMatches(re, text) {
        const out = [];
        const g = new RegExp(re.source, re.flags.includes("g") ? re.flags : re.flags + "g");
        let m;
        while ((m = g.exec(text)) !== null) {
            out.push(m);
            if (m[0].length === 0) g.lastIndex += 1;
        }
        return out;
    }

}
