{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.customNixOSModules.localLlm;

  # The assistant the shell uses: the base model with its runtime parameters
  # baked in. The shell talks to Ollama's OpenAI-compatible endpoint, which
  # ignores Ollama-specific options (threads, answer length), so they live in
  # the model itself.
  modelfile = pkgs.writeText "${cfg.assistantName}.Modelfile" ''
    FROM ${cfg.model}
    PARAMETER num_ctx ${toString cfg.contextLength}
    PARAMETER num_thread ${toString cfg.threads}
    PARAMETER num_predict ${toString cfg.maxAnswerTokens}
    PARAMETER temperature 0.2
  '';
  ollamaPackage =
    {
      cpu = pkgs.ollama;
      vulkan = pkgs.ollama-vulkan;
      rocm = pkgs.ollama-rocm;
      cuda = pkgs.ollama-cuda;
    }
    .${cfg.acceleration};
in
{
  options.customNixOSModules.localLlm = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Run a small local LLM (Ollama) as the nixbook-shell assistant: the
        Intelligence tab (left sidebar) then defaults to it and answers
        questions about this machine's configuration (keybinds, enabled
        modules, installed packages, where to change things) from facts
        generated by Nix, checking its answers against them.

        Tuned to stay unnoticeable: idle CPU/IO scheduling (it only uses spare
        CPU), a thread cap, one model loaded, and the model unloaded after
        `keepAlive` of inactivity (its RAM is freed).
      '';
    };
    model = lib.mkOption {
      type = lib.types.str;
      default = "qwen2.5:1.5b";
      description = ''
        Ollama model the assistant is built from. qwen2.5:1.5b was the
        lightest (CPU/RAM) that answered every question of the configuration
        test correctly with the shell's retrieval and answer checks; qwen3:1.7b
        does too at ~1.5x the RAM; anything smaller missed questions.
      '';
    };
    assistantName = lib.mkOption {
      type = lib.types.str;
      default = "nixbook-assistant";
      description = "Name of the derived model (model + parameters) the shell selects.";
    };
    acceleration = lib.mkOption {
      type = lib.types.enum [
        "cpu"
        "vulkan"
        "rocm"
        "cuda"
      ];
      default = "cpu";
      description = ''
        Ollama build. "cpu" keeps the GPU free for the desktop; a 1.5B model
        answers in ~2 s on 4 threads.
      '';
    };
    threads = lib.mkOption {
      type = lib.types.ints.positive;
      default = 4;
      description = "CPU threads the model may use.";
    };
    contextLength = lib.mkOption {
      type = lib.types.ints.positive;
      default = 4096;
      description = "Context window (the assistant's prompt is ~400 tokens plus the chat).";
    };
    maxAnswerTokens = lib.mkOption {
      type = lib.types.ints.positive;
      default = 256;
      description = "Answer length cap (also stops a small model looping).";
    };
    keepAlive = lib.mkOption {
      type = lib.types.str;
      default = "3m";
      description = "How long the model stays in RAM after the last question.";
    };
  };

  # On a machine that also runs customNixOSModules.ollama (big GPU models,
  # e.g. anya), the assistant model is just added to that server: its
  # package, host and tuning win, and it is not deprioritised.
  config = lib.mkIf cfg.enable {
    services.ollama = {
      enable = true;
      package = lib.mkDefault ollamaPackage;
      host = lib.mkDefault "127.0.0.1";
      port = 11434;
      loadModels = [ cfg.model ];
      environmentVariables = lib.mapAttrs (_: lib.mkDefault) {
        OLLAMA_KEEP_ALIVE = cfg.keepAlive;
        OLLAMA_MAX_LOADED_MODELS = "1";
        OLLAMA_NUM_PARALLEL = "1";
        OLLAMA_CONTEXT_LENGTH = toString cfg.contextLength;
      };
    };

    # Only spare CPU and IO: the desktop and anything else always win.
    systemd.services.ollama.serviceConfig =
      lib.mkIf (!(config.customNixOSModules.ollama.enable or false))
        {
          Nice = 19;
          CPUSchedulingPolicy = "idle";
          IOSchedulingClass = "idle";
          CPUWeight = "idle";
        };
    systemd.services.ollama-model-loader.serviceConfig = {
      Nice = 19;
      IOSchedulingClass = "idle";
    };

    # Derive the assistant model once the base model is downloaded (the
    # loader pulls in the background after boot; this waits for it). `exec`,
    # not `oneshot`: a switch would otherwise wait for the whole download.
    # Re-created on each boot and whenever the Modelfile changes (cheap).
    systemd.services.nixbook-assistant-model = {
      description = "Create the ${cfg.assistantName} Ollama model";
      wantedBy = [ "multi-user.target" ];
      after = [ "ollama.service" ];
      requires = [ "ollama.service" ];
      environment = {
        OLLAMA_HOST = "127.0.0.1:11434";
        HOME = "/tmp";
      };
      serviceConfig = {
        Type = "exec";
        DynamicUser = true;
        PrivateTmp = true;
        Nice = 19;
        IOSchedulingClass = "idle";
        TimeoutStartSec = "2h";
      };
      path = [ config.services.ollama.package ];
      script = ''
        until ollama show ${lib.escapeShellArg cfg.model} >/dev/null 2>&1; do
          sleep 15
        done
        ollama create ${lib.escapeShellArg cfg.assistantName} -f ${modelfile}
      '';
    };
  };
}
