{
  pkgs,
  lib,
  config,
  ...
}:
let
  cfg = config.customNixOSModules.wolf;
in
{
  options.customNixOSModules.wolf = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        whether to enable wolf globally or not
      '';
    };
    steamVolumePath = lib.mkOption {
      type = lib.types.str;
      default = "/home/khoa/.local/share/Steam";
      description = ''
        The path to the Steam directory on the host to mount into the Wolf container.
      '';
    };
  };
  config = lib.mkIf cfg.enable {
    networking.firewall = {
      allowedTCPPorts = [
        47984
        47989
        47999
        48010
      ];
      allowedUDPPorts = [
        47998
        47999
        48000
        48001
        48002
        48003
        48004
        48005
        48006
        48007
        48008
        48009
        48010
        48100
        48200
      ];
    };

    services.avahi = {
      enable = true;
      nssmdns4 = true;
      publish = {
        enable = true;
        addresses = true;
        userServices = true;
      };
    };

    # uinput config
    boot.kernelModules = [
      "uinput"
      "uhid"
    ];

    # Règle UDEV for uinput
    services.udev.extraRules = ''
      KERNEL=="uinput", MODE="0660", GROUP="docker", OPTIONS+="static_node=uinput"
    '';

    # Containers
    virtualisation.oci-containers.containers."wolf-wolf" = {
      image = "ghcr.io/games-on-whales/wolf:stable";
      environment = {
        "HOST_APPS_STATE_FOLDER" = "/etc/wolf";
        "XDG_RUNTIME_DIR" = "/tmp/sockets";
        "TZ" = "Europe/Paris";
        "WOLF_ENCODER_NODE" = "/dev/dri/renderD128";
        "WOLF_RENDER_NODE" = "/dev/dri/renderD128";
        "WOLF_LOG_LEVEL" = "DEBUG";
        "LIBVA_DRIVER_NAME" = "radeonsi";
        "WOLF_DISABLE_HW_ACCEL" = "false";
      };
      volumes = [
        "/dev/:/dev:rw"
        "/etc/wolf/:/etc/wolf:rw"
        "/run/udev:/run/udev:rw"
        "/tmp/sockets:/tmp/sockets:rw"
        "/var/run/docker.sock:/var/run/docker.sock:rw"
        "/etc/localtime:/etc/localtime:ro"
        "${cfg.steamVolumePath}:${cfg.steamVolumePath}:rw"
        "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
        "/run/systemd/system:/run/systemd/system"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
        "--privileged"
        "--device-cgroup-rule=c 13:* rmw"
        "--cap-add=NET_ADMIN"
        "--cap-add=SYS_ADMIN"
        "--cap-add=SYS_RESOURCE"
        "--env=LD_LIBRARY_PATH=/run/opengl-driver/lib:/run/opengl-driver-32/lib"
      ];
    };
    systemd.services."docker-wolf-wolf" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      partOf = [
        "docker-compose-wolf-root.target"
      ];
      wantedBy = [
        "docker-compose-wolf-root.target"
      ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-wolf-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
