{
  pkgs,
  lib,
  config,
  ...
}:
let
  cfg = config.customNixOSModules.wolf;
in
{
  options.customNixOSModules.wolf = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        whether to enable wolf globally or not
      '';
    };
    hostAppsStateFolder = lib.mkOption {
      type = lib.types.str;
      default = "/etc/wolf";
      description = ''
        The path to the Wolf application state folder on the host.
      '';
    };
    den.port = lib.mkOption {
      type = lib.types.port;
      default = 8080;
      description = ''
        The port on which wolf-den web UI listens.
      '';
    };
  };
  config = lib.mkIf cfg.enable {
    networking.firewall = {
      allowedTCPPorts = [
        47984
        47989
        47999
        48010
      ]
      ++ [
        cfg.den.port
      ];
      allowedUDPPorts = [
        47998
        47999
        48000
        48001
        48002
        48003
        48004
        48005
        48006
        48007
        48008
        48009
        48010
        48100
        48200
      ];
    };

    services.avahi = {
      enable = true;
      nssmdns4 = true;
      publish = {
        enable = true;
        addresses = true;
        userServices = true;
      };
    };

    # uinput config
    boot.kernelModules = [
      "uinput"
      "uhid"
    ];

    # Règle UDEV for uinput
    services.udev.extraRules = ''
      KERNEL=="uinput", MODE="0660", GROUP="docker", OPTIONS+="static_node=uinput"
    '';
    systemd = {
      tmpfiles.rules = [
        "d ${cfg.hostAppsStateFolder} 0755 root root -"
        "d ${cfg.hostAppsStateFolder}/wolf-den 0755 root root -"
        "d ${cfg.hostAppsStateFolder}/covers 0755 root root -"
        "d /tmp/sockets 0755 root root -"
        "d /var/run/wolf 0755 root root -"
      ]
      ++ [
        "d ${cfg.hostAppsStateFolder}/wolf-den 0755 root root -"
        "d ${cfg.hostAppsStateFolder}/covers 0755 root root -"
      ];
      services."podman-wolf-wolf" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "5s";
          RestartSteps = lib.mkOverride 90 9;
          ExecStartPre = lib.mkOverride 90 [
            "-${pkgs.podman}/bin/podman kill --all"
            "-${pkgs.podman}/bin/podman rm --all -f"
          ];
          ExecStopPost = lib.mkOverride 90 [
            "-${pkgs.podman}/bin/podman rm -f wolf-wolf"
            "-${pkgs.podman}/bin/podman rm -f WolfPulseAudio"
          ];
        };
        partOf = [
          "docker-compose-wolf-root.target"
        ];
        wantedBy = [
          "docker-compose-wolf-root.target"
        ];
      };
      services."podman-wolf-den" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "5s";
          RestartSteps = lib.mkOverride 90 9;
          ExecStartPre = lib.mkOverride 90 "${pkgs.writeShellScript "wait-wolf-socket" ''
            timeout=30
            elapsed=0
            while [ ! -S /var/run/wolf/wolf.sock ]; do
              if [ "$elapsed" -ge "$timeout" ]; then
                echo "Timed out waiting for Wolf socket"
                exit 1
              fi
              sleep 1
              elapsed=$((elapsed + 1))
            done
            echo "Wolf socket is ready"
          ''}";
          ExecStopPost = lib.mkOverride 90 "-${pkgs.podman}/bin/podman rm -f wolf-den";
        };
        after = [ "podman-wolf-wolf.service" ];
        requires = [ "podman-wolf-wolf.service" ];
        partOf = [
          "docker-compose-wolf-root.target"
        ];
        wantedBy = [
          "docker-compose-wolf-root.target"
        ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      targets."docker-compose-wolf-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Containers
    virtualisation.oci-containers.containers."wolf-wolf" = {
      image = "ghcr.io/games-on-whales/wolf:stable";
      environment = {
        "HOST_APPS_STATE_FOLDER" = cfg.hostAppsStateFolder;
        "XDG_RUNTIME_DIR" = "/tmp/sockets";
        "TZ" = "Europe/Paris";
        "WOLF_ENCODER_NODE" = "/dev/dri/renderD128";
        "WOLF_RENDER_NODE" = "/dev/dri/renderD128";
        "WOLF_LOG_LEVEL" = "DEBUG";
        "LIBVA_DRIVER_NAME" = "radeonsi";
        "WOLF_DISABLE_HW_ACCEL" = "false";
        "WOLF_SOCKET_PATH" = "/var/run/wolf/wolf.sock";
      };
      volumes = [
        "/dev/:/dev:rw"
        "${cfg.hostAppsStateFolder}/:${cfg.hostAppsStateFolder}:rw"
        "/run/udev:/run/udev:rw"
        "/tmp/sockets:/tmp/sockets:rw"
        "/run/podman/podman.sock:/var/run/docker.sock:rw"
        "/etc/localtime:/etc/localtime:ro"
        "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
        "/run/systemd/system:/run/systemd/system"
        "/var/run/wolf:/var/run/wolf"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
        "--privileged"
        "--device-cgroup-rule=c 13:* rmw"
        "--cap-add=NET_ADMIN"
        "--cap-add=SYS_ADMIN"
        "--cap-add=SYS_RESOURCE"
        "--env=LD_LIBRARY_PATH=/run/opengl-driver/lib:/run/opengl-driver-32/lib"
      ];
    };

    # Wolf Den - Web UI for managing Wolf
    virtualisation.oci-containers.containers."wolf-den" = {
      image = "ghcr.io/games-on-whales/wolf-den:stable";
      environment = {
        "WOLF_SOCKET_PATH" = "/var/run/wolf/wolf.sock";
        "ASPNETCORE_URLS" = "http://0.0.0.0:${toString cfg.den.port}";
      };
      volumes = [
        "${cfg.hostAppsStateFolder}/wolf-den:/app/wolf-den/"
        "/var/run/wolf:/var/run/wolf"
        "${cfg.hostAppsStateFolder}/covers:/etc/wolf/covers"
      ];
      log-driver = "journald";
      dependsOn = [ "wolf-wolf" ];
      extraOptions = [
        "--network=host"
      ];
    };
  };
}
