{ ... }:
{
  imports = [
    ./atuinConfig.nix
    ./cliTools.nix
    ./desktopApps.nix
    ./devTools.nix
    ./dmsConfig.nix
    ./dolphinConfig.nix
    ./fastfetchConfig.nix
    ./fcitx5Config.nix
    ./fontConfig.nix
    ./gitConfig.nix
    ./goji.nix
    ./gtkConfig.nix
    ./hyprland
    ./k9sConfig.nix
    ./kittyConfig.nix
    ./kubeswitchConfig.nix
    ./kubeTools.nix
    ./mpvConfig.nix
    ./niri
    ./opencodeConfig.nix
    ./nixvim
    ./rtkConfig.nix
    ./sshConfig.nix
    ./starshipConfig.nix
    ./stylixConfig.nix
    ./sway
    ./thunderbirdConfig.nix
    ./vscode
    ./zshConfig.nix
  ];
}
