#!/usr/bin/env bash
# Apply cursor theme + size. Usage: set-cursor-theme.sh <theme> [size]
# Niri's own cursor is handled separately via qssettings/shell.kdl.
set -u

theme="$1"
size="${2:-24}"
[[ -z $theme ]] && {
  echo "usage: $0 <cursor-theme> [size]" >&2
  exit 1
}

gsettings set org.gnome.desktop.interface cursor-theme "$theme" 2>/dev/null
gsettings set org.gnome.desktop.interface cursor-size "$size" 2>/dev/null

# Default cursor inheritance for X11/legacy apps
mkdir -p "$HOME/.icons/default"
cat >"$HOME/.icons/default/index.theme" <<EOF
[Icon Theme]
Name=Default
Comment=Default cursor theme (generated by shell settings)
Inherits=$theme
EOF

exit 0
